extern __ev64_opaque__ __ev_abs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabs") ));
extern __ev64_opaque__ __ev_addiw( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evaddiw") ));
extern __ev64_opaque__ __ev_addsmfaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddsmiaaw") ));
extern __ev64_opaque__ __ev_addsmiaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddsmiaaw") ));
extern __ev64_opaque__ __ev_addssfaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddssiaaw") ));
extern __ev64_opaque__ __ev_addssiaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddssiaaw") ));
extern __ev64_opaque__ __ev_addumfaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddumiaaw") ));
extern __ev64_opaque__ __ev_addumiaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddumiaaw") ));
extern __ev64_opaque__ __ev_addusfaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddusiaaw") ));
extern __ev64_opaque__ __ev_addusiaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddusiaaw") ));
extern __ev64_opaque__ __ev_addw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddw") ));
extern int __ev_all_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2058, 1, "evcmpeq") ));
extern int __ev_all_fs_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmpeq") ));
extern int __ev_all_fs_gt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmpgt") ));
extern int __ev_all_fs_lt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmplt") ));
extern int __ev_all_fs_tst_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststeq") ));
extern int __ev_all_fs_tst_gt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststgt") ));
extern int __ev_all_fs_tst_lt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststlt") ));
extern int __ev_all_gts( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpgts") ));
extern int __ev_all_gtu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpgtu") ));
extern int __ev_all_lts( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmplts") ));
extern int __ev_all_ltu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpltu") ));
extern __ev64_opaque__ __ev_and( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evand") ));
extern __ev64_opaque__ __ev_andc( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evandc") ));
extern int __ev_any_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2058, 1, "evcmpeq") ));
extern int __ev_any_fs_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmpeq") ));
extern int __ev_any_fs_gt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmpgt") ));
extern int __ev_any_fs_lt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmplt") ));
extern int __ev_any_fs_tst_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststeq") ));
extern int __ev_any_fs_tst_gt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststgt") ));
extern int __ev_any_fs_tst_lt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststlt") ));
extern int __ev_any_gts( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpgts") ));
extern int __ev_any_gtu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpgtu") ));
extern int __ev_any_lts( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmplts") ));
extern int __ev_any_ltu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpltu") ));
extern __ev64_opaque__ __ev_cntlsw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evcntlsw") ));
extern __ev64_opaque__ __ev_cntlzw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evcntlzw") ));
extern __ev64_opaque__ __ev_divws( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdivws") ));
extern __ev64_opaque__ __ev_divwu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdivwu") ));
extern __ev64_opaque__ __ev_eqv( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "eveqv") ));
extern __ev64_opaque__ __ev_extsb( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evextsb") ));
extern __ev64_opaque__ __ev_extsh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evextsh") ));
extern __ev64_opaque__ __ev_fsabs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsabs") ));
extern __ev64_opaque__ __ev_fsadd( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 1, "evfsadd") ));
extern __ev64_opaque__ __ev_fscfsf( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfscfsf") ));
extern __ev64_opaque__ __ev_fscfsi( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfscfsi") ));
extern __ev64_opaque__ __ev_fscfuf( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfscfuf") ));
extern __ev64_opaque__ __ev_fscfui( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfscfui") ));
extern __ev64_opaque__ __ev_fsctsf( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsctsf") ));
extern __ev64_opaque__ __ev_fsctsi( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsctsi") ));
extern __ev64_opaque__ __ev_fsctsiz( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsctsiz") ));
extern __ev64_opaque__ __ev_fsctuf( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsctuf") ));
extern __ev64_opaque__ __ev_fsctui( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsctui") ));
extern __ev64_opaque__ __ev_fsctuiz( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsctuiz") ));
extern __ev64_opaque__ __ev_fsdiv( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 1, "evfsdiv") ));
extern __ev64_opaque__ __ev_fsmul( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 1, "evfsmul") ));
extern __ev64_opaque__ __ev_fsnabs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsnabs") ));
extern __ev64_opaque__ __ev_fsneg( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evfsneg") ));
extern __ev64_opaque__ __ev_fssub( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 1, "evfssub") ));
extern short __ev_get_s16( __ev64_opaque__,  int) __attribute__((intrinsic_function(2030, 0, "lhax") ));
extern unsigned short __ev_get_u16( __ev64_opaque__,  int) __attribute__((intrinsic_function(2030, 0, "lhzx") ));
extern __ev64_opaque__ __ev_ldd( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evldd") ));
extern __ev64_opaque__ __ev_lddepx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlddepx") ));
extern __ev64_opaque__ __ev_lddx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlddx") ));
extern __ev64_opaque__ __ev_ldh( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evldh") ));
extern __ev64_opaque__ __ev_ldhx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evldhx") ));
extern __ev64_opaque__ __ev_ldw( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evldw") ));
extern __ev64_opaque__ __ev_ldwx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evldwx") ));
extern __ev64_opaque__ __ev_lhhesplat( unsigned short*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlhhesplat") ));
extern __ev64_opaque__ __ev_lhhesplatx( unsigned short*,  int) __attribute__((intrinsic_function(2003, 1, "evlhhesplatx") ));
extern __ev64_opaque__ __ev_lhhossplat( unsigned short*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlhhossplat") ));
extern __ev64_opaque__ __ev_lhhossplatx( unsigned short*,  int) __attribute__((intrinsic_function(2003, 1, "evlhhossplatx") ));
extern __ev64_opaque__ __ev_lhhousplat( unsigned short*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlhhousplat") ));
extern __ev64_opaque__ __ev_lhhousplatx( unsigned short*,  int) __attribute__((intrinsic_function(2003, 1, "evlhhousplatx") ));
extern int __ev_lower_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2058, 1, "evcmpeq") ));
extern int __ev_lower_fs_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmpeq") ));
extern int __ev_lower_fs_gt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmpgt") ));
extern int __ev_lower_fs_lt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmplt") ));
extern int __ev_lower_fs_tst_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststeq") ));
extern int __ev_lower_fs_tst_gt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststgt") ));
extern int __ev_lower_fs_tst_lt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststlt") ));
extern int __ev_lower_gts( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpgts") ));
extern int __ev_lower_gtu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpgtu") ));
extern int __ev_lower_lts( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmplts") ));
extern int __ev_lower_ltu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpltu") ));
extern __ev64_opaque__ __ev_lwhe( unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwhe") ));
extern __ev64_opaque__ __ev_lwhex( unsigned int*,  int) __attribute__((intrinsic_function(2008, 1, "evlwhex") ));
extern __ev64_opaque__ __ev_lwhos( unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwhos") ));
extern __ev64_opaque__ __ev_lwhosx( unsigned int*,  int) __attribute__((intrinsic_function(2003, 1, "evlwhosx") ));
extern __ev64_opaque__ __ev_lwhou( unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwhou") ));
extern __ev64_opaque__ __ev_lwhoux( unsigned int*,  int) __attribute__((intrinsic_function(2003, 1, "evlwhoux") ));
extern __ev64_opaque__ __ev_lwhsplat( unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwhsplat") ));
extern __ev64_opaque__ __ev_lwhsplatx( unsigned int*,  int) __attribute__((intrinsic_function(2003, 1, "evlwhsplatx") ));
extern __ev64_opaque__ __ev_lwwsplat( unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwwsplat") ));
extern __ev64_opaque__ __ev_lwwsplatx( unsigned int*,  int) __attribute__((intrinsic_function(2003, 1, "evlwwsplatx") ));
extern __ev64_opaque__ __ev_mergehi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 1, "evmergehi") ));
extern __ev64_opaque__ __ev_mergehilo( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 1, "evmergehilo") ));
extern __ev64_opaque__ __ev_mergelo( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 1, "evmergelo") ));
extern __ev64_opaque__ __ev_mergelohi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 1, "evmergelohi") ));
extern __ev64_opaque__ __ev_mhegsmfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhegsmfaa") ));
extern __ev64_opaque__ __ev_mhegsmfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhegsmfan") ));
extern __ev64_opaque__ __ev_mhegsmiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhegsmiaa") ));
extern __ev64_opaque__ __ev_mhegsmian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhegsmian") ));
extern __ev64_opaque__ __ev_mhegumfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhegumiaa") ));
extern __ev64_opaque__ __ev_mhegumfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhegumian") ));
extern __ev64_opaque__ __ev_mhegumiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhegumiaa") ));
extern __ev64_opaque__ __ev_mhegumian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhegumian") ));
extern __ev64_opaque__ __ev_mhesmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhesmf") ));
extern __ev64_opaque__ __ev_mhesmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhesmfa") ));
extern __ev64_opaque__ __ev_mhesmfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhesmfaaw") ));
extern __ev64_opaque__ __ev_mhesmfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhesmfanw") ));
extern __ev64_opaque__ __ev_mhesmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhesmi") ));
extern __ev64_opaque__ __ev_mhesmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhesmia") ));
extern __ev64_opaque__ __ev_mhesmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhesmiaaw") ));
extern __ev64_opaque__ __ev_mhesmianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhesmianw") ));
extern __ev64_opaque__ __ev_mhessf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhessf") ));
extern __ev64_opaque__ __ev_mhessfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhessfa") ));
extern __ev64_opaque__ __ev_mhessfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhessfaaw") ));
extern __ev64_opaque__ __ev_mhessfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhessfanw") ));
extern __ev64_opaque__ __ev_mhessiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhessiaaw") ));
extern __ev64_opaque__ __ev_mhessianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhessianw") ));
extern __ev64_opaque__ __ev_mheumf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheumi") ));
extern __ev64_opaque__ __ev_mheumfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheumia") ));
extern __ev64_opaque__ __ev_mheumfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheumiaaw") ));
extern __ev64_opaque__ __ev_mheumfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheumianw") ));
extern __ev64_opaque__ __ev_mheumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheumi") ));
extern __ev64_opaque__ __ev_mheumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheumia") ));
extern __ev64_opaque__ __ev_mheumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheumiaaw") ));
extern __ev64_opaque__ __ev_mheumianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheumianw") ));
extern __ev64_opaque__ __ev_mheusfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheusiaaw") ));
extern __ev64_opaque__ __ev_mheusfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheusianw") ));
extern __ev64_opaque__ __ev_mheusiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheusiaaw") ));
extern __ev64_opaque__ __ev_mheusianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmheusianw") ));
extern __ev64_opaque__ __ev_mhogsmfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhogsmfaa") ));
extern __ev64_opaque__ __ev_mhogsmfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhogsmfan") ));
extern __ev64_opaque__ __ev_mhogsmiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhogsmiaa") ));
extern __ev64_opaque__ __ev_mhogsmian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhogsmian") ));
extern __ev64_opaque__ __ev_mhogumfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhogumiaa") ));
extern __ev64_opaque__ __ev_mhogumfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhogumian") ));
extern __ev64_opaque__ __ev_mhogumiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhogumiaa") ));
extern __ev64_opaque__ __ev_mhogumian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhogumian") ));
extern __ev64_opaque__ __ev_mhosmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhosmf") ));
extern __ev64_opaque__ __ev_mhosmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhosmfa") ));
extern __ev64_opaque__ __ev_mhosmfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhosmfaaw") ));
extern __ev64_opaque__ __ev_mhosmfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhosmfanw") ));
extern __ev64_opaque__ __ev_mhosmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhosmi") ));
extern __ev64_opaque__ __ev_mhosmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhosmia") ));
extern __ev64_opaque__ __ev_mhosmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhosmiaaw") ));
extern __ev64_opaque__ __ev_mhosmianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhosmianw") ));
extern __ev64_opaque__ __ev_mhossf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhossf") ));
extern __ev64_opaque__ __ev_mhossfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhossfa") ));
extern __ev64_opaque__ __ev_mhossfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhossfaaw") ));
extern __ev64_opaque__ __ev_mhossfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhossfanw") ));
extern __ev64_opaque__ __ev_mhossiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhossiaaw") ));
extern __ev64_opaque__ __ev_mhossianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhossianw") ));
extern __ev64_opaque__ __ev_mhoumf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhoumi") ));
extern __ev64_opaque__ __ev_mhoumfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhoumia") ));
extern __ev64_opaque__ __ev_mhoumfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhoumiaaw") ));
extern __ev64_opaque__ __ev_mhoumfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhoumianw") ));
extern __ev64_opaque__ __ev_mhoumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhoumi") ));
extern __ev64_opaque__ __ev_mhoumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhoumia") ));
extern __ev64_opaque__ __ev_mhoumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhoumiaaw") ));
extern __ev64_opaque__ __ev_mhoumianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhoumianw") ));
extern __ev64_opaque__ __ev_mhousfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhousiaaw") ));
extern __ev64_opaque__ __ev_mhousfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhousianw") ));
extern __ev64_opaque__ __ev_mhousiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhousiaaw") ));
extern __ev64_opaque__ __ev_mhousianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmhousianw") ));
extern __ev64_opaque__ __ev_mra( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evmra") ));
extern __ev64_opaque__ __ev_mwhgsmfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2038, 0, "evmwhsmf") ));
extern __ev64_opaque__ __ev_mwhgsmfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2039, 0, "evmwhsmf") ));
extern __ev64_opaque__ __ev_mwhgsmiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2038, 0, "evmwhsmi") ));
extern __ev64_opaque__ __ev_mwhgsmian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2039, 0, "evmwhsmi") ));
extern __ev64_opaque__ __ev_mwhgssfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2038, 0, "evmwhssf") ));
extern __ev64_opaque__ __ev_mwhgssfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2039, 0, "evmwhssf") ));
extern __ev64_opaque__ __ev_mwhgumfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2040, 0, "evmwumiaa") ));
extern __ev64_opaque__ __ev_mwhgumfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2040, 0, "evmwumian") ));
extern __ev64_opaque__ __ev_mwhgumiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2040, 0, "evmwumiaa") ));
extern __ev64_opaque__ __ev_mwhgumian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2040, 0, "evmwumian") ));
extern __ev64_opaque__ __ev_mwhsmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhsmf") ));
extern __ev64_opaque__ __ev_mwhsmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhsmfa") ));
#ifndef __SPE2__
extern __ev64_opaque__ __ev_mwhsmfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2033, 0, "evmwhsmf") ));
#endif
#ifndef __SPE2__
extern __ev64_opaque__ __ev_mwhsmfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2042, 0, "evmwhsmf") ));
#endif
extern __ev64_opaque__ __ev_mwhsmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhsmi") ));
extern __ev64_opaque__ __ev_mwhsmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhsmia") ));
extern __ev64_opaque__ __ev_mwhsmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2033, 0, "evmwhsmi") ));
extern __ev64_opaque__ __ev_mwhsmianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2042, 0, "evmwhsmi") ));
extern __ev64_opaque__ __ev_mwhssf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhssf") ));
extern __ev64_opaque__ __ev_mwhssfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhssfa") ));
#ifndef __SPE2__
extern __ev64_opaque__ __ev_mwhssfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2033, 0, "evmwhssf") ));
#endif
#ifndef __SPE2__
extern __ev64_opaque__ __ev_mwhssfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2034, 0, "evmwhssf") ));
#endif
extern __ev64_opaque__ __ev_mwhssiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2033, 0, "evmwhsmi") ));
extern __ev64_opaque__ __ev_mwhssianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2034, 0, "evmwhsmi") ));
extern __ev64_opaque__ __ev_mwhumf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhumi") ));
extern __ev64_opaque__ __ev_mwhumfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhumia") ));
extern __ev64_opaque__ __ev_mwhumfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2041, 0, "evaddumiaaw") ));
extern __ev64_opaque__ __ev_mwhumfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2043, 0, "evsubfumiaaw") ));
extern __ev64_opaque__ __ev_mwhumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhumi") ));
extern __ev64_opaque__ __ev_mwhumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwhumia") ));
extern __ev64_opaque__ __ev_mwhumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2041, 0, "evaddumiaaw") ));
extern __ev64_opaque__ __ev_mwhumianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2043, 0, "evsubfumiaaw") ));
extern __ev64_opaque__ __ev_mwhusfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2041, 0, "evaddusiaaw") ));
extern __ev64_opaque__ __ev_mwhusfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2043, 0, "evsubfusiaaw") ));
extern __ev64_opaque__ __ev_mwhusiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2041, 0, "evaddusiaaw") ));
extern __ev64_opaque__ __ev_mwhusianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2043, 0, "evsubfusiaaw") ));
extern __ev64_opaque__ __ev_mwlsmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlsmiaaw") ));
extern __ev64_opaque__ __ev_mwlsmianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlsmianw") ));
extern __ev64_opaque__ __ev_mwlssiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlssiaaw") ));
extern __ev64_opaque__ __ev_mwlssianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlssianw") ));
extern __ev64_opaque__ __ev_mwlumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlumi") ));
extern __ev64_opaque__ __ev_mwlumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlumia") ));
extern __ev64_opaque__ __ev_mwlumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlumiaaw") ));
extern __ev64_opaque__ __ev_mwlumianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlumianw") ));
extern __ev64_opaque__ __ev_mwlusiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlusiaaw") ));
extern __ev64_opaque__ __ev_mwlusianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwlusianw") ));
extern __ev64_opaque__ __ev_mwsmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwsmf") ));
extern __ev64_opaque__ __ev_mwsmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwsmfa") ));
extern __ev64_opaque__ __ev_mwsmfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwsmfaa") ));
extern __ev64_opaque__ __ev_mwsmfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwsmfan") ));
extern __ev64_opaque__ __ev_mwsmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwsmi") ));
extern __ev64_opaque__ __ev_mwsmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwsmia") ));
extern __ev64_opaque__ __ev_mwsmiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwsmiaa") ));
extern __ev64_opaque__ __ev_mwsmian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwsmian") ));
extern __ev64_opaque__ __ev_mwssf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwssf") ));
extern __ev64_opaque__ __ev_mwssfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwssfa") ));
extern __ev64_opaque__ __ev_mwssfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwssfaa") ));
extern __ev64_opaque__ __ev_mwssfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwssfan") ));
extern __ev64_opaque__ __ev_mwumf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwumi") ));
extern __ev64_opaque__ __ev_mwumfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwumia") ));
extern __ev64_opaque__ __ev_mwumfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwumiaa") ));
extern __ev64_opaque__ __ev_mwumfan( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwumian") ));
extern __ev64_opaque__ __ev_mwumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwumi") ));
extern __ev64_opaque__ __ev_mwumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwumia") ));
extern __ev64_opaque__ __ev_mwumiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwumiaa") ));
extern __ev64_opaque__ __ev_mwumian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2003, 0, "evmwumian") ));
extern __ev64_opaque__ __ev_nand( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evnand") ));
extern __ev64_opaque__ __ev_neg( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evneg") ));
extern __ev64_opaque__ __ev_nor( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evnor") ));
extern __ev64_opaque__ __ev_or( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evor") ));
extern __ev64_opaque__ __ev_orc( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evorc") ));
extern __ev64_opaque__ __ev_rlw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrlw") ));
extern __ev64_opaque__ __ev_rlwi( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evrlwi") ));
extern __ev64_opaque__ __ev_rndw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrndw") ));
extern __ev64_opaque__ __ev_select_eq( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evcmpeq") ));
extern __ev64_opaque__ __ev_select_fs_eq( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evfscmpeq") ));
extern __ev64_opaque__ __ev_select_fs_gt( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evfscmpgt") ));
extern __ev64_opaque__ __ev_select_fs_lt( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evfscmplt") ));
extern __ev64_opaque__ __ev_select_fs_tst_eq( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evfststeq") ));
extern __ev64_opaque__ __ev_select_fs_tst_gt( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evfststgt") ));
extern __ev64_opaque__ __ev_select_fs_tst_lt( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evfststlt") ));
extern __ev64_opaque__ __ev_select_gts( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evcmpgts") ));
extern __ev64_opaque__ __ev_select_gtu( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evcmpgtu") ));
extern __ev64_opaque__ __ev_select_lts( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evcmplts") ));
extern __ev64_opaque__ __ev_select_ltu( __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2019, 1, "evcmpltu") ));
extern __ev64_opaque__ __ev_set_lower_s32( __ev64_opaque__,  int) __attribute__((intrinsic_function(2014, 1, "evmergehilo") ));
extern __ev64_opaque__ __ev_set_lower_sfix32_s32( __ev64_opaque__,  int) __attribute__((intrinsic_function(2014, 1, "evmergehilo") ));
extern __ev64_opaque__ __ev_set_lower_u32( __ev64_opaque__,  unsigned int) __attribute__((intrinsic_function(2014, 1, "evmergehilo") ));
extern __ev64_opaque__ __ev_set_lower_ufix32_u32( __ev64_opaque__,  unsigned int) __attribute__((intrinsic_function(2014, 1, "evmergehilo") ));
extern __ev64_opaque__ __ev_set_s16( __ev64_opaque__,  short,  int) __attribute__((intrinsic_function(2023, 0, "sthx") ));
extern __ev64_opaque__ __ev_set_u16( __ev64_opaque__,  unsigned short,  int) __attribute__((intrinsic_function(2023, 0, "sthx") ));
extern __ev64_opaque__ __ev_set_upper_s32( __ev64_opaque__,  int) __attribute__((intrinsic_function(2015, 1, "evmergelo") ));
extern __ev64_opaque__ __ev_set_upper_sfix32_s32( __ev64_opaque__,  int) __attribute__((intrinsic_function(2015, 1, "evmergelo") ));
extern __ev64_opaque__ __ev_set_upper_u32( __ev64_opaque__,  unsigned int) __attribute__((intrinsic_function(2015, 1, "evmergelo") ));
extern __ev64_opaque__ __ev_set_upper_ufix32_u32( __ev64_opaque__,  unsigned int) __attribute__((intrinsic_function(2015, 1, "evmergelo") ));
extern __ev64_opaque__ __ev_slw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evslw") ));
extern __ev64_opaque__ __ev_slwi( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evslwi") ));
extern __ev64_opaque__ __ev_splatfi( const signed int) __attribute__((intrinsic_function(2016, 1, "evsplatfi") ));
extern __ev64_opaque__ __ev_splati( const signed int) __attribute__((intrinsic_function(2016, 1, "evsplati") ));
extern __ev64_opaque__ __ev_srwis( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsrwis") ));
extern __ev64_opaque__ __ev_srwiu( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsrwiu") ));
extern __ev64_opaque__ __ev_srws( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsrws") ));
extern __ev64_opaque__ __ev_srwu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsrwu") ));
extern void __ev_stdd( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstdd") ));
extern void __ev_stddepx( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstddepx") ));
extern void __ev_stddx( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstddx") ));
extern void __ev_stdh( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstdh") ));
extern void __ev_stdhx( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstdhx") ));
extern void __ev_stdw( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstdw") ));
extern void __ev_stdwx( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstdwx") ));
extern void __ev_stwhe( __ev64_opaque__,  unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwhe") ));
extern void __ev_stwhex( __ev64_opaque__,  unsigned int*,  int) __attribute__((intrinsic_function(2026, 0, "evstwhex") ));
extern void __ev_stwho( __ev64_opaque__,  unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwho") ));
extern void __ev_stwhox( __ev64_opaque__,  unsigned int*,  int) __attribute__((intrinsic_function(2026, 0, "evstwhox") ));
extern void __ev_stwwe( __ev64_opaque__,  unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwwe") ));
extern void __ev_stwwex( __ev64_opaque__,  unsigned int*,  int) __attribute__((intrinsic_function(2026, 0, "evstwwex") ));
extern void __ev_stwwo( __ev64_opaque__,  unsigned int*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwwo") ));
extern void __ev_stwwox( __ev64_opaque__,  unsigned int*,  int) __attribute__((intrinsic_function(2026, 0, "evstwwox") ));
extern __ev64_opaque__ __ev_subfsmfaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfsmiaaw") ));
extern __ev64_opaque__ __ev_subfsmiaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfsmiaaw") ));
extern __ev64_opaque__ __ev_subfssfaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfssiaaw") ));
extern __ev64_opaque__ __ev_subfssiaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfssiaaw") ));
extern __ev64_opaque__ __ev_subfumfaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfumiaaw") ));
extern __ev64_opaque__ __ev_subfumiaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfumiaaw") ));
extern __ev64_opaque__ __ev_subfusfaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfusiaaw") ));
extern __ev64_opaque__ __ev_subfusiaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfusiaaw") ));
extern __ev64_opaque__ __ev_subfw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 1, "evsubfw") ));
extern __ev64_opaque__ __ev_subifw( const unsigned int,  __ev64_opaque__) __attribute__((intrinsic_function(2059, 1, "evsubifw") ));
extern __ev64_opaque__ __ev_subiw( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2061, 1, "evsubifw") ));
extern __ev64_opaque__ __ev_subw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2060, 1, "evsubfw") ));
extern int __ev_upper_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2058, 1, "evcmpeq") ));
extern int __ev_upper_fs_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmpeq") ));
extern int __ev_upper_fs_gt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmpgt") ));
extern int __ev_upper_fs_lt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfscmplt") ));
extern int __ev_upper_fs_tst_eq( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststeq") ));
extern int __ev_upper_fs_tst_gt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststgt") ));
extern int __ev_upper_fs_tst_lt( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evfststlt") ));
extern int __ev_upper_gts( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpgts") ));
extern int __ev_upper_gtu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpgtu") ));
extern int __ev_upper_lts( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmplts") ));
extern int __ev_upper_ltu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2009, 1, "evcmpltu") ));
extern __ev64_opaque__ __ev_xor( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evxor") ));
