extern unsigned int __brinc( unsigned int,  unsigned int) __attribute__((intrinsic_function(2008, 1, "brinc") ));
extern __ev64_opaque__ __ev_absb( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsb") ));
extern __ev64_opaque__ __ev_absbs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsbs") ));
extern __ev64_opaque__ __ev_absdifsb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsdifsb") ));
extern __ev64_opaque__ __ev_absdifsh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsdifsh") ));
extern __ev64_opaque__ __ev_absdifsw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsdifsw") ));
extern __ev64_opaque__ __ev_absdifub( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsdifub") ));
extern __ev64_opaque__ __ev_absdifuh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsdifuh") ));
extern __ev64_opaque__ __ev_absdifuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsdifuw") ));
extern __ev64_opaque__ __ev_absh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabsh") ));
extern __ev64_opaque__ __ev_abshs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabshs") ));
extern __ev64_opaque__ __ev_abss( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evabss") ));
extern __ev64_opaque__ __ev_add2subf2h( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evadd2subf2h") ));
extern __ev64_opaque__ __ev_add2subf2hss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evadd2subf2hss") ));
extern __ev64_opaque__ __ev_add2subf2hus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evadd2subf2hus") ));
extern __ev64_opaque__ __ev_addaa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddaa") ));
extern __ev64_opaque__ __ev_addb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddb") ));
extern __ev64_opaque__ __ev_addbss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddbss") ));
extern __ev64_opaque__ __ev_addbus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddbus") ));
extern __ev64_opaque__ __ev_addh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddh") ));
extern __ev64_opaque__ __ev_addhss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddhss") ));
extern __ev64_opaque__ __ev_addhus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddhus") ));
extern __ev64_opaque__ __ev_addhx( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddhx") ));
extern __ev64_opaque__ __ev_addhxss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddhxss") ));
extern __ev64_opaque__ __ev_addhxus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddhxus") ));
extern __ev64_opaque__ __ev_addib( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evaddib") ));
extern __ev64_opaque__ __ev_addih( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evaddih") ));
extern __ev64_opaque__ __ev_addssiaa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddssiaa") ));
extern __ev64_opaque__ __ev_addsubfh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfh") ));
extern __ev64_opaque__ __ev_addsubfhss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfhss") ));
extern __ev64_opaque__ __ev_addsubfhus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfhus") ));
extern __ev64_opaque__ __ev_addsubfhx( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfhx") ));
extern __ev64_opaque__ __ev_addsubfhxss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfhxss") ));
extern __ev64_opaque__ __ev_addsubfhxus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfhxus") ));
extern __ev64_opaque__ __ev_addsubfw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfw") ));
extern __ev64_opaque__ __ev_addsubfwss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfwss") ));
extern __ev64_opaque__ __ev_addsubfwus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfwus") ));
extern __ev64_opaque__ __ev_addsubfwx( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfwx") ));
extern __ev64_opaque__ __ev_addsubfwxss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfwxss") ));
extern __ev64_opaque__ __ev_addsubfwxus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddsubfwxus") ));
extern __ev64_opaque__ __ev_addusiaa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evaddusiaa") ));
extern __ev64_opaque__ __ev_addwss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddwss") ));
extern __ev64_opaque__ __ev_addwus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddwus") ));
extern __ev64_opaque__ __ev_addwx( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddwx") ));
extern __ev64_opaque__ __ev_addwxss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddwxss") ));
extern __ev64_opaque__ __ev_addwxus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evaddwxus") ));
extern __ev64_opaque__ __ev_avgbs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavgbs") ));
extern __ev64_opaque__ __ev_avgbsr( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavgbsr") ));
extern __ev64_opaque__ __ev_avgbu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavgbu") ));
extern __ev64_opaque__ __ev_avgbur( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavgbur") ));
extern __ev64_opaque__ __ev_avghs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavghs") ));
extern __ev64_opaque__ __ev_avghsr( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavghsr") ));
extern __ev64_opaque__ __ev_avghu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavghu") ));
extern __ev64_opaque__ __ev_avghur( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavghur") ));
extern __ev64_opaque__ __ev_avgws( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavgws") ));
extern __ev64_opaque__ __ev_avgwsr( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavgwsr") ));
extern __ev64_opaque__ __ev_avgwu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavgwu") ));
extern __ev64_opaque__ __ev_avgwur( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evavgwur") ));
extern __ev64_opaque__ __ev_clrbe( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evclrbe") ));
extern __ev64_opaque__ __ev_clrbo( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evclrbo") ));
extern __ev64_opaque__ __ev_clrh( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evclrh") ));
extern __ev64_opaque__ __ev_cntlsh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evcntlsh") ));
extern __ev64_opaque__ __ev_cntlzh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evcntlzh") ));
extern __ev64_opaque__ __ev_divs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdivs") ));
extern __ev64_opaque__ __ev_divu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdivu") ));
extern __ev64_opaque__ __ev_divwsf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdivwsf") ));
extern __ev64_opaque__ __ev_divwuf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdivwuf") ));
extern __ev64_opaque__ __ev_dlveb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdlveb") ));
extern __ev64_opaque__ __ev_dlveh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdlveh") ));
extern __ev64_opaque__ __ev_dlveob( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdlveob") ));
extern __ev64_opaque__ __ev_dlveoh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdlveoh") ));
extern __ev64_opaque__ __ev_dlvob( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdlvob") ));
extern __ev64_opaque__ __ev_dlvoeb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdlvoeb") ));
extern __ev64_opaque__ __ev_dlvoeh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdlvoeh") ));
extern __ev64_opaque__ __ev_dlvoh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdlvoh") ));
extern __ev64_opaque__ __ev_dotp4hasmfaalw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasmfaalw") ));
extern __ev64_opaque__ __ev_dotp4hasmfaauw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasmfaauw") ));
extern __ev64_opaque__ __ev_dotp4hasmflw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hasmflw") ));
extern __ev64_opaque__ __ev_dotp4hasmflwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasmflwa") ));
extern __ev64_opaque__ __ev_dotp4hasmfuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hasmfuw") ));
extern __ev64_opaque__ __ev_dotp4hasmfuwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasmfuwa") ));
extern __ev64_opaque__ __ev_dotp4hasmiaalw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasmiaalw") ));
extern __ev64_opaque__ __ev_dotp4hasmiaauw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasmiaauw") ));
extern __ev64_opaque__ __ev_dotp4hasmilw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hasmilw") ));
extern __ev64_opaque__ __ev_dotp4hasmilwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasmilwa") ));
extern __ev64_opaque__ __ev_dotp4hasmiuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hasmiuw") ));
extern __ev64_opaque__ __ev_dotp4hasmiuwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasmiuwa") ));
extern __ev64_opaque__ __ev_dotp4hassfaalw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hassfaalw") ));
extern __ev64_opaque__ __ev_dotp4hassfaauw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hassfaauw") ));
extern __ev64_opaque__ __ev_dotp4hassflw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hassflw") ));
extern __ev64_opaque__ __ev_dotp4hassflwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hassflwa") ));
extern __ev64_opaque__ __ev_dotp4hassfuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hassfuw") ));
extern __ev64_opaque__ __ev_dotp4hassfuwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hassfuwa") ));
extern __ev64_opaque__ __ev_dotp4hassiaalw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hassiaalw") ));
extern __ev64_opaque__ __ev_dotp4hassiaauw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hassiaauw") ));
extern __ev64_opaque__ __ev_dotp4hassilw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hassilw") ));
extern __ev64_opaque__ __ev_dotp4hassilwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hassilwa") ));
extern __ev64_opaque__ __ev_dotp4hassiuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hassiuw") ));
extern __ev64_opaque__ __ev_dotp4hassiuwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hassiuwa") ));
extern __ev64_opaque__ __ev_dotp4hasumiaalw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasumiaalw") ));
extern __ev64_opaque__ __ev_dotp4hasumiaauw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasumiaauw") ));
extern __ev64_opaque__ __ev_dotp4hasumilw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hasumilw") ));
extern __ev64_opaque__ __ev_dotp4hasumilwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasumilwa") ));
extern __ev64_opaque__ __ev_dotp4hasumiuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hasumiuw") ));
extern __ev64_opaque__ __ev_dotp4hasumiuwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasumiuwa") ));
extern __ev64_opaque__ __ev_dotp4hasusiaalw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasusiaalw") ));
extern __ev64_opaque__ __ev_dotp4hasusiaauw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasusiaauw") ));
extern __ev64_opaque__ __ev_dotp4hasusilw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hasusilw") ));
extern __ev64_opaque__ __ev_dotp4hasusilwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasusilwa") ));
extern __ev64_opaque__ __ev_dotp4hasusiuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hasusiuw") ));
extern __ev64_opaque__ __ev_dotp4hasusiuwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hasusiuwa") ));
extern __ev64_opaque__ __ev_dotp4haumiaalw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4haumiaalw") ));
extern __ev64_opaque__ __ev_dotp4haumiaauw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4haumiaauw") ));
extern __ev64_opaque__ __ev_dotp4haumilw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4haumilw") ));
extern __ev64_opaque__ __ev_dotp4haumilwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4haumilwa") ));
extern __ev64_opaque__ __ev_dotp4haumiuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4haumiuw") ));
extern __ev64_opaque__ __ev_dotp4haumiuwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4haumiuwa") ));
extern __ev64_opaque__ __ev_dotp4hausiaalw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hausiaalw") ));
extern __ev64_opaque__ __ev_dotp4hausiaauw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hausiaauw") ));
extern __ev64_opaque__ __ev_dotp4hausilw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hausilw") ));
extern __ev64_opaque__ __ev_dotp4hausilwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hausilwa") ));
extern __ev64_opaque__ __ev_dotp4hausiuw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hausiuw") ));
extern __ev64_opaque__ __ev_dotp4hausiuwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hausiuwa") ));
extern __ev64_opaque__ __ev_dotp4hgasmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hgasmf") ));
extern __ev64_opaque__ __ev_dotp4hgasmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hgasmfa") ));
extern __ev64_opaque__ __ev_dotp4hgasmfaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hgasmfaa") ));
extern __ev64_opaque__ __ev_dotp4hgasmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hgasmi") ));
extern __ev64_opaque__ __ev_dotp4hgasmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hgasmia") ));
extern __ev64_opaque__ __ev_dotp4hgasmiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hgasmiaa") ));
extern __ev64_opaque__ __ev_dotp4hgasumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hgasumi") ));
extern __ev64_opaque__ __ev_dotp4hgasumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hgasumia") ));
extern __ev64_opaque__ __ev_dotp4hgasumiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hgasumiaa") ));
extern __ev64_opaque__ __ev_dotp4hgaumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotp4hgaumi") ));
extern __ev64_opaque__ __ev_dotp4hgaumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hgaumia") ));
extern __ev64_opaque__ __ev_dotp4hgaumiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotp4hgaumiaa") ));
extern __ev64_opaque__ __ev_dotpbasmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpbasmi") ));
extern __ev64_opaque__ __ev_dotpbasmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpbasmia") ));
extern __ev64_opaque__ __ev_dotpbasmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpbasmiaaw") ));
extern __ev64_opaque__ __ev_dotpbasumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpbasumi") ));
extern __ev64_opaque__ __ev_dotpbasumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpbasumia") ));
extern __ev64_opaque__ __ev_dotpbasumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpbasumiaaw") ));
extern __ev64_opaque__ __ev_dotpbaumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpbaumi") ));
extern __ev64_opaque__ __ev_dotpbaumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpbaumia") ));
extern __ev64_opaque__ __ev_dotpbaumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpbaumiaaw") ));
extern __ev64_opaque__ __ev_dotphasmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphasmf") ));
extern __ev64_opaque__ __ev_dotphasmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphasmfa") ));
extern __ev64_opaque__ __ev_dotphasmfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphasmfaaw") ));
extern __ev64_opaque__ __ev_dotphasmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphasmi") ));
extern __ev64_opaque__ __ev_dotphasmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphasmia") ));
extern __ev64_opaque__ __ev_dotphasmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphasmiaaw") ));
extern __ev64_opaque__ __ev_dotphassf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphassf") ));
extern __ev64_opaque__ __ev_dotphassfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphassfa") ));
extern __ev64_opaque__ __ev_dotphassfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphassfaaw") ));
extern __ev64_opaque__ __ev_dotphassi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphassi") ));
extern __ev64_opaque__ __ev_dotphassia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphassia") ));
extern __ev64_opaque__ __ev_dotphassiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphassiaaw") ));
extern __ev64_opaque__ __ev_dotphasumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphasumi") ));
extern __ev64_opaque__ __ev_dotphasumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphasumia") ));
extern __ev64_opaque__ __ev_dotphasumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphasumiaaw") ));
extern __ev64_opaque__ __ev_dotphasusi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphasusi") ));
extern __ev64_opaque__ __ev_dotphasusia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphasusia") ));
extern __ev64_opaque__ __ev_dotphasusiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphasusiaaw") ));
extern __ev64_opaque__ __ev_dotphaumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphaumi") ));
extern __ev64_opaque__ __ev_dotphaumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphaumia") ));
extern __ev64_opaque__ __ev_dotphaumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphaumiaaw") ));
extern __ev64_opaque__ __ev_dotphausi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphausi") ));
extern __ev64_opaque__ __ev_dotphausia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphausia") ));
extern __ev64_opaque__ __ev_dotphausiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphausiaaw") ));
extern __ev64_opaque__ __ev_dotphcsmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphcsmf") ));
extern __ev64_opaque__ __ev_dotphcsmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphcsmfa") ));
extern __ev64_opaque__ __ev_dotphcsmfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphcsmfaaw") ));
extern __ev64_opaque__ __ev_dotphcsmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphcsmi") ));
extern __ev64_opaque__ __ev_dotphcsmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphcsmia") ));
extern __ev64_opaque__ __ev_dotphcsmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphcsmiaaw") ));
extern __ev64_opaque__ __ev_dotphcssf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphcssf") ));
extern __ev64_opaque__ __ev_dotphcssfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphcssfa") ));
extern __ev64_opaque__ __ev_dotphcssfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphcssfaaw") ));
extern __ev64_opaque__ __ev_dotphcssi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphcssi") ));
extern __ev64_opaque__ __ev_dotphcssia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphcssia") ));
extern __ev64_opaque__ __ev_dotphcssiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphcssiaaw") ));
extern __ev64_opaque__ __ev_dotphssmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphssmf") ));
extern __ev64_opaque__ __ev_dotphssmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphssmfa") ));
extern __ev64_opaque__ __ev_dotphssmfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphssmfaaw") ));
extern __ev64_opaque__ __ev_dotphssmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphssmi") ));
extern __ev64_opaque__ __ev_dotphssmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphssmia") ));
extern __ev64_opaque__ __ev_dotphssmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphssmiaaw") ));
extern __ev64_opaque__ __ev_dotphsssf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphsssf") ));
extern __ev64_opaque__ __ev_dotphsssfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphsssfa") ));
extern __ev64_opaque__ __ev_dotphsssfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphsssfaaw") ));
extern __ev64_opaque__ __ev_dotphsssi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphsssi") ));
extern __ev64_opaque__ __ev_dotphsssia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphsssia") ));
extern __ev64_opaque__ __ev_dotphsssiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphsssiaaw") ));
extern __ev64_opaque__ __ev_dotphxasmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphxasmf") ));
extern __ev64_opaque__ __ev_dotphxasmfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphxasmfa") ));
extern __ev64_opaque__ __ev_dotphxasmfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphxasmfaaw") ));
extern __ev64_opaque__ __ev_dotphxasmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphxasmi") ));
extern __ev64_opaque__ __ev_dotphxasmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphxasmia") ));
extern __ev64_opaque__ __ev_dotphxasmiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphxasmiaaw") ));
extern __ev64_opaque__ __ev_dotphxassf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphxassf") ));
extern __ev64_opaque__ __ev_dotphxassfa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphxassfa") ));
extern __ev64_opaque__ __ev_dotphxassfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphxassfaaw") ));
extern __ev64_opaque__ __ev_dotphxassi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotphxassi") ));
extern __ev64_opaque__ __ev_dotphxassia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphxassia") ));
extern __ev64_opaque__ __ev_dotphxassiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotphxassiaaw") ));
extern __ev64_opaque__ __ev_dotpwasmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwasmi") ));
extern __ev64_opaque__ __ev_dotpwasmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwasmia") ));
extern __ev64_opaque__ __ev_dotpwasmiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwasmiaa") ));
extern __ev64_opaque__ __ev_dotpwassi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwassi") ));
extern __ev64_opaque__ __ev_dotpwassia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwassia") ));
extern __ev64_opaque__ __ev_dotpwassiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwassiaa") ));
extern __ev64_opaque__ __ev_dotpwasumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwasumi") ));
extern __ev64_opaque__ __ev_dotpwasumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwasumia") ));
extern __ev64_opaque__ __ev_dotpwasumiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwasumiaa") ));
extern __ev64_opaque__ __ev_dotpwasusi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwasusi") ));
extern __ev64_opaque__ __ev_dotpwasusia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwasusia") ));
extern __ev64_opaque__ __ev_dotpwasusiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwasusiaa") ));
extern __ev64_opaque__ __ev_dotpwaumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwaumi") ));
extern __ev64_opaque__ __ev_dotpwaumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwaumia") ));
extern __ev64_opaque__ __ev_dotpwaumiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwaumiaa") ));
extern __ev64_opaque__ __ev_dotpwausi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwausi") ));
extern __ev64_opaque__ __ev_dotpwausia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwausia") ));
extern __ev64_opaque__ __ev_dotpwausiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwausiaa") ));
extern __ev64_opaque__ __ev_dotpwssmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwssmi") ));
extern __ev64_opaque__ __ev_dotpwssmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwssmia") ));
extern __ev64_opaque__ __ev_dotpwssmiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwssmiaa") ));
extern __ev64_opaque__ __ev_dotpwsssiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwsssiaa") ));
extern __ev64_opaque__ __ev_dotpwxasmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwxasmi") ));
extern __ev64_opaque__ __ev_dotpwxasmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwxasmia") ));
extern __ev64_opaque__ __ev_dotpwxasmiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwxasmiaa") ));
extern __ev64_opaque__ __ev_dotpwxassi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evdotpwxassi") ));
extern __ev64_opaque__ __ev_dotpwxassia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwxassia") ));
extern __ev64_opaque__ __ev_dotpwxassiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evdotpwxassiaa") ));
extern __ev64_opaque__ __ev_extsbh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evextsbh") ));
extern __ev64_opaque__ __ev_extsw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evextsw") ));
extern __ev64_opaque__ __ev_extzb( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evextzb") ));
extern __ev64_opaque__ __ev_ilveh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evilveh") ));
extern __ev64_opaque__ __ev_ilveoh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evilveoh") ));
extern __ev64_opaque__ __ev_ilvhih( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evilvhih") ));
extern __ev64_opaque__ __ev_ilvhiloh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evilvhiloh") ));
extern __ev64_opaque__ __ev_ilvloh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evilvloh") ));
extern __ev64_opaque__ __ev_ilvlohih( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evilvlohih") ));
extern __ev64_opaque__ __ev_ilvoeh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evilvoeh") ));
extern __ev64_opaque__ __ev_ilvoh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evilvoh") ));
extern __ev64_opaque__ __ev_insb( __ev64_opaque__,  const unsigned int,  const unsigned int) __attribute__((intrinsic_function(2087, 0, "evinsb") ));
extern __ev64_opaque__ __ev_insh( __ev64_opaque__,  const unsigned int,  const unsigned int) __attribute__((intrinsic_function(2087, 0, "evinsh") ));
extern __ev64_opaque__ __ev_lbbsplatb( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlbbsplatb") ));
extern __ev64_opaque__ __ev_lbbsplatbu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlbbsplatbu") ));
extern __ev64_opaque__ __ev_lbbsplatbux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlbbsplatbux") ));
extern __ev64_opaque__ __ev_lbbsplatbx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlbbsplatbx") ));
extern __ev64_opaque__ __ev_ldb( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evldb") ));
extern __ev64_opaque__ __ev_ldbu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evldbu") ));
extern __ev64_opaque__ __ev_ldbux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evldbux") ));
extern __ev64_opaque__ __ev_ldbx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evldbx") ));
extern __ev64_opaque__ __ev_lddu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlddu") ));
extern __ev64_opaque__ __ev_lddux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlddux") ));
extern __ev64_opaque__ __ev_ldhu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evldhu") ));
extern __ev64_opaque__ __ev_ldhux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evldhux") ));
extern __ev64_opaque__ __ev_ldwu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evldwu") ));
extern __ev64_opaque__ __ev_ldwux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evldwux") ));
extern __ev64_opaque__ __ev_lhhesplatu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlhhesplatu") ));
extern __ev64_opaque__ __ev_lhhesplatux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlhhesplatux") ));
extern __ev64_opaque__ __ev_lhhossplatu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlhhossplatu") ));
extern __ev64_opaque__ __ev_lhhossplatux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlhhossplatux") ));
extern __ev64_opaque__ __ev_lhhousplatu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlhhousplatu") ));
extern __ev64_opaque__ __ev_lhhousplatux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlhhousplatux") ));
extern __ev64_opaque__ __ev_lhhsplath( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlhhsplath") ));
extern __ev64_opaque__ __ev_lhhsplathu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlhhsplathu") ));
extern __ev64_opaque__ __ev_lhhsplathux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlhhsplathux") ));
extern __ev64_opaque__ __ev_lhhsplathx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlhhsplathx") ));
extern __ev64_opaque__ __ev_lvsl( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlvsl") ));
extern __ev64_opaque__ __ev_lvsr( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlvsr") ));
extern __ev64_opaque__ __ev_lwbe( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwbe") ));
extern __ev64_opaque__ __ev_lwbeu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwbeu") ));
extern __ev64_opaque__ __ev_lwbeux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwbeux") ));
extern __ev64_opaque__ __ev_lwbex( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlwbex") ));
extern __ev64_opaque__ __ev_lwbos( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwbos") ));
extern __ev64_opaque__ __ev_lwbosu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwbosu") ));
extern __ev64_opaque__ __ev_lwbosux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwbosux") ));
extern __ev64_opaque__ __ev_lwbosx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlwbosx") ));
extern __ev64_opaque__ __ev_lwbou( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwbou") ));
extern __ev64_opaque__ __ev_lwbouu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwbouu") ));
extern __ev64_opaque__ __ev_lwbouux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwbouux") ));
extern __ev64_opaque__ __ev_lwboux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwboux") ));
extern __ev64_opaque__ __ev_lwbsplatw( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwbsplatw") ));
extern __ev64_opaque__ __ev_lwbsplatwu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwbsplatwu") ));
extern __ev64_opaque__ __ev_lwbsplatwux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwbsplatwux") ));
extern __ev64_opaque__ __ev_lwbsplatwx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlwbsplatwx") ));
extern __ev64_opaque__ __ev_lwheu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwheu") ));
extern __ev64_opaque__ __ev_lwheux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwheux") ));
extern __ev64_opaque__ __ev_lwhosu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwhosu") ));
extern __ev64_opaque__ __ev_lwhosux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwhosux") ));
extern __ev64_opaque__ __ev_lwhouu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwhouu") ));
extern __ev64_opaque__ __ev_lwhouux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwhouux") ));
extern __ev64_opaque__ __ev_lwhsplatu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwhsplatu") ));
extern __ev64_opaque__ __ev_lwhsplatux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwhsplatux") ));
extern __ev64_opaque__ __ev_lwhsplatw( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 1, "evlwhsplatw") ));
extern __ev64_opaque__ __ev_lwhsplatwu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwhsplatwu") ));
extern __ev64_opaque__ __ev_lwhsplatwux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwhsplatwux") ));
extern __ev64_opaque__ __ev_lwhsplatwx( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 1, "evlwhsplatwx") ));
extern __ev64_opaque__ __ev_lwwsplatu( __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2053, 0, "evlwwsplatu") ));
extern __ev64_opaque__ __ev_lwwsplatux( __ev64_opaque__*,  int) __attribute__((intrinsic_function(2008, 0, "evlwwsplatux") ));
extern __ev64_opaque__ __ev_mar( void) __attribute__((intrinsic_function(2083, 1, "evmar") ));
extern __ev64_opaque__ __ev_maxbpsh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxbpsh") ));
extern __ev64_opaque__ __ev_maxbpuh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxbpuh") ));
extern __ev64_opaque__ __ev_maxbs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxbs") ));
extern __ev64_opaque__ __ev_maxbu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxbu") ));
extern __ev64_opaque__ __ev_maxhpsw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxhpsw") ));
extern __ev64_opaque__ __ev_maxhpuw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxhpuw") ));
extern __ev64_opaque__ __ev_maxhs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxhs") ));
extern __ev64_opaque__ __ev_maxhu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxhu") ));
extern __ev64_opaque__ __ev_maxwpsd( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxwpsd") ));
extern __ev64_opaque__ __ev_maxwpud( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxwpud") ));
extern __ev64_opaque__ __ev_maxws( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxws") ));
extern __ev64_opaque__ __ev_maxwu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmaxwu") ));
extern __ev64_opaque__ __ev_mbesmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmbesmi") ));
extern __ev64_opaque__ __ev_mbesmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbesmia") ));
extern __ev64_opaque__ __ev_mbesmiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbesmiaah") ));
extern __ev64_opaque__ __ev_mbesmianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbesmianh") ));
extern __ev64_opaque__ __ev_mbessiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbessiaah") ));
extern __ev64_opaque__ __ev_mbessianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbessianh") ));
extern __ev64_opaque__ __ev_mbesumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmbesumi") ));
extern __ev64_opaque__ __ev_mbesumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbesumia") ));
extern __ev64_opaque__ __ev_mbesumiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbesumiaah") ));
extern __ev64_opaque__ __ev_mbesumianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbesumianh") ));
extern __ev64_opaque__ __ev_mbesusiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbesusiaah") ));
extern __ev64_opaque__ __ev_mbesusianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbesusianh") ));
extern __ev64_opaque__ __ev_mbeumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmbeumi") ));
extern __ev64_opaque__ __ev_mbeumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbeumia") ));
extern __ev64_opaque__ __ev_mbeumiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbeumiaah") ));
extern __ev64_opaque__ __ev_mbeumianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbeumianh") ));
extern __ev64_opaque__ __ev_mbeusiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbeusiaah") ));
extern __ev64_opaque__ __ev_mbeusianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbeusianh") ));
extern __ev64_opaque__ __ev_mbosmi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmbosmi") ));
extern __ev64_opaque__ __ev_mbosmia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbosmia") ));
extern __ev64_opaque__ __ev_mbosmiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbosmiaah") ));
extern __ev64_opaque__ __ev_mbosmianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbosmianh") ));
extern __ev64_opaque__ __ev_mbossiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbossiaah") ));
extern __ev64_opaque__ __ev_mbossianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbossianh") ));
extern __ev64_opaque__ __ev_mbosumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmbosumi") ));
extern __ev64_opaque__ __ev_mbosumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbosumia") ));
extern __ev64_opaque__ __ev_mbosumiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbosumiaah") ));
extern __ev64_opaque__ __ev_mbosumianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbosumianh") ));
extern __ev64_opaque__ __ev_mbosusiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbosusiaah") ));
extern __ev64_opaque__ __ev_mbosusianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbosusianh") ));
extern __ev64_opaque__ __ev_mboumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmboumi") ));
extern __ev64_opaque__ __ev_mboumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmboumia") ));
extern __ev64_opaque__ __ev_mboumiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmboumiaah") ));
extern __ev64_opaque__ __ev_mboumianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmboumianh") ));
extern __ev64_opaque__ __ev_mbousiaah( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbousiaah") ));
extern __ev64_opaque__ __ev_mbousianh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmbousianh") ));
extern __ev64_opaque__ __ev_mhesumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhesumi") ));
extern __ev64_opaque__ __ev_mhesumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhesumia") ));
extern __ev64_opaque__ __ev_mhesumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhesumiaaw") ));
extern __ev64_opaque__ __ev_mhesumianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhesumianw") ));
extern __ev64_opaque__ __ev_mhesusiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhesusiaaw") ));
extern __ev64_opaque__ __ev_mhesusianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhesusianw") ));
extern __ev64_opaque__ __ev_mhosumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhosumi") ));
extern __ev64_opaque__ __ev_mhosumia( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhosumia") ));
extern __ev64_opaque__ __ev_mhosumiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhosumiaaw") ));
extern __ev64_opaque__ __ev_mhosumianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhosumianw") ));
extern __ev64_opaque__ __ev_mhosusiaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhosusiaaw") ));
extern __ev64_opaque__ __ev_mhosusianw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmhosusianw") ));
extern __ev64_opaque__ __ev_mhsmf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhsmf") ));
extern __ev64_opaque__ __ev_mhsmfr( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhsmfr") ));
extern __ev64_opaque__ __ev_mhssf( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhssf") ));
extern __ev64_opaque__ __ev_mhssfr( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhssfr") ));
extern __ev64_opaque__ __ev_mhssi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhssi") ));
extern __ev64_opaque__ __ev_mhsusi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhsusi") ));
extern __ev64_opaque__ __ev_mhumi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhumi") ));
extern __ev64_opaque__ __ev_mhusi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmhusi") ));
extern __ev64_opaque__ __ev_minbpsh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminbpsh") ));
extern __ev64_opaque__ __ev_minbpuh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminbpuh") ));
extern __ev64_opaque__ __ev_minbs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminbs") ));
extern __ev64_opaque__ __ev_minbu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminbu") ));
extern __ev64_opaque__ __ev_minhpsw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminhpsw") ));
extern __ev64_opaque__ __ev_minhpuw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminhpuw") ));
extern __ev64_opaque__ __ev_minhs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminhs") ));
extern __ev64_opaque__ __ev_minhu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminhu") ));
extern __ev64_opaque__ __ev_minwpsd( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminwpsd") ));
extern __ev64_opaque__ __ev_minwpud( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminwpud") ));
extern __ev64_opaque__ __ev_minws( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminws") ));
extern __ev64_opaque__ __ev_minwu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evminwu") ));
extern __ev64_opaque__ __ev_mwhsmfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmwhsmfaaw") ));
extern __ev64_opaque__ __ev_mwhsmfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwhsmfanw") ));
extern __ev64_opaque__ __ev_mwhsmfr( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwhsmfr") ));
extern __ev64_opaque__ __ev_mwhsmfra( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmwhsmfra") ));
extern __ev64_opaque__ __ev_mwhsmfraaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmwhsmfraaw") ));
extern __ev64_opaque__ __ev_mwhsmfranw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwhsmfranw") ));
extern __ev64_opaque__ __ev_mwhssfaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmwhssfaaw") ));
extern __ev64_opaque__ __ev_mwhssfanw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwhssfanw") ));
extern __ev64_opaque__ __ev_mwhssfr( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwhssfr") ));
extern __ev64_opaque__ __ev_mwhssfra( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmwhssfra") ));
extern __ev64_opaque__ __ev_mwhssfraaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmwhssfraaw") ));
extern __ev64_opaque__ __ev_mwhssfranw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwhssfranw") ));
extern __ev64_opaque__ __ev_mwssiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmwssiaa") ));
extern __ev64_opaque__ __ev_mwssian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwssian") ));
extern __ev64_opaque__ __ev_mwssiw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwssiw") ));
extern __ev64_opaque__ __ev_mwusiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evmwusiaa") ));
extern __ev64_opaque__ __ev_mwusian( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwusian") ));
extern __ev64_opaque__ __ev_mwusiw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evmwusiw") ));
extern __ev64_opaque__ __ev_negb( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evnegb") ));
extern __ev64_opaque__ __ev_negbs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evnegbs") ));
extern __ev64_opaque__ __ev_negh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evnegh") ));
extern __ev64_opaque__ __ev_neghs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evneghs") ));
extern __ev64_opaque__ __ev_negs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evnegs") ));
extern __ev64_opaque__ __ev_perm( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evperm") ));
extern __ev64_opaque__ __ev_perm2( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evperm2") ));
extern __ev64_opaque__ __ev_perm3( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evperm3") ));
extern __ev64_opaque__ __ev_pkshsbs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evpkshsbs") ));
extern __ev64_opaque__ __ev_pkshubs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evpkshubs") ));
extern __ev64_opaque__ __ev_pkswishs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evpkswishs") ));
extern __ev64_opaque__ __ev_pkswshs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evpkswshs") ));
extern __ev64_opaque__ __ev_pkswuhs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evpkswuhs") ));
extern __ev64_opaque__ __ev_pkuhubs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evpkuhubs") ));
extern __ev64_opaque__ __ev_pkuwuhs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evpkuwuhs") ));
extern __ev64_opaque__ __ev_popcntb( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evpopcntb") ));
extern __ev64_opaque__ __ev_rlb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrlb") ));
extern __ev64_opaque__ __ev_rlbi( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evrlbi") ));
extern __ev64_opaque__ __ev_rlh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrlh") ));
extern __ev64_opaque__ __ev_rlhi( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evrlhi") ));
extern __ev64_opaque__ __ev_rndh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrndh") ));
extern __ev64_opaque__ __ev_rndhss( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrndhss") ));
extern __ev64_opaque__ __ev_rndhus( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrndhus") ));
extern __ev64_opaque__ __ev_rndwss( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrndwss") ));
extern __ev64_opaque__ __ev_rndwus( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evrndwus") ));
extern __ev64_opaque__ __ev_sad2sh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsad2sh") ));
extern __ev64_opaque__ __ev_sad2sha( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsad2sha") ));
extern __ev64_opaque__ __ev_sad2shaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsad2shaaw") ));
extern __ev64_opaque__ __ev_sad2uh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsad2uh") ));
extern __ev64_opaque__ __ev_sad2uha( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsad2uha") ));
extern __ev64_opaque__ __ev_sad2uhaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsad2uhaaw") ));
extern __ev64_opaque__ __ev_sad4sb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsad4sb") ));
extern __ev64_opaque__ __ev_sad4sba( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsad4sba") ));
extern __ev64_opaque__ __ev_sad4sbaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsad4sbaaw") ));
extern __ev64_opaque__ __ev_sad4ub( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsad4ub") ));
extern __ev64_opaque__ __ev_sad4uba( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsad4uba") ));
extern __ev64_opaque__ __ev_sad4ubaaw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsad4ubaaw") ));
extern __ev64_opaque__ __ev_sadsw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsadsw") ));
extern __ev64_opaque__ __ev_sadswa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsadswa") ));
extern __ev64_opaque__ __ev_sadswaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsadswaa") ));
extern __ev64_opaque__ __ev_saduw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsaduw") ));
extern __ev64_opaque__ __ev_saduwa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsaduwa") ));
extern __ev64_opaque__ __ev_saduwaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2008, 0, "evsaduwaa") ));
extern __ev64_opaque__ __ev_satsbub( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatsbub") ));
extern __ev64_opaque__ __ev_satsdsw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatsdsw") ));
extern __ev64_opaque__ __ev_satsduw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatsduw") ));
extern __ev64_opaque__ __ev_satshsb( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatshsb") ));
extern __ev64_opaque__ __ev_satshub( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatshub") ));
extern __ev64_opaque__ __ev_satshuh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatshuh") ));
extern __ev64_opaque__ __ev_satswsh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatswsh") ));
extern __ev64_opaque__ __ev_satswuh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatswuh") ));
extern __ev64_opaque__ __ev_satswuw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatswuw") ));
extern __ev64_opaque__ __ev_satubsb( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatubsb") ));
extern __ev64_opaque__ __ev_satuduw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatuduw") ));
extern __ev64_opaque__ __ev_satuhsh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatuhsh") ));
extern __ev64_opaque__ __ev_satuhub( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatuhub") ));
extern __ev64_opaque__ __ev_satuwsw( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatuwsw") ));
extern __ev64_opaque__ __ev_satuwuh( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsatuwuh") ));
extern __ev64_opaque__ __ev_selbit( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evselbit") ));
extern __ev64_opaque__ __ev_selbitm0( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evselbitm0") ));
extern __ev64_opaque__ __ev_selbitm1( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evselbitm1") ));
extern __ev64_opaque__ __ev_seteqb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evseteqb") ));
extern __ev64_opaque__ __ev_seteqh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evseteqh") ));
extern __ev64_opaque__ __ev_seteqw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evseteqw") ));
extern __ev64_opaque__ __ev_setgtbs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetgtbs") ));
extern __ev64_opaque__ __ev_setgtbu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetgtbu") ));
extern __ev64_opaque__ __ev_setgths( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetgths") ));
extern __ev64_opaque__ __ev_setgthu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetgthu") ));
extern __ev64_opaque__ __ev_setgtws( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetgtws") ));
extern __ev64_opaque__ __ev_setgtwu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetgtwu") ));
extern __ev64_opaque__ __ev_setltbs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetltbs") ));
extern __ev64_opaque__ __ev_setltbu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetltbu") ));
extern __ev64_opaque__ __ev_setlths( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetlths") ));
extern __ev64_opaque__ __ev_setlthu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetlthu") ));
extern __ev64_opaque__ __ev_setltws( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetltws") ));
extern __ev64_opaque__ __ev_setltwu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsetltwu") ));
extern __ev64_opaque__ __ev_sl( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsl") ));
extern __ev64_opaque__ __ev_slb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evslb") ));
extern __ev64_opaque__ __ev_slbi( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evslbi") ));
extern __ev64_opaque__ __ev_slh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evslh") ));
extern __ev64_opaque__ __ev_slhi( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evslhi") ));
extern __ev64_opaque__ __ev_sli( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsli") ));
extern __ev64_opaque__ __ev_sloi( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsloi") ));
extern __ev64_opaque__ __ev_splatb( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsplatb") ));
extern __ev64_opaque__ __ev_splatfih( const signed int) __attribute__((intrinsic_function(2016, 1, "evsplatfih") ));
extern __ev64_opaque__ __ev_splath( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsplath") ));
extern __ev64_opaque__ __ev_splatib( const signed int) __attribute__((intrinsic_function(2016, 1, "evsplatib") ));
extern __ev64_opaque__ __ev_splatih( const signed int) __attribute__((intrinsic_function(2016, 1, "evsplatih") ));
extern __ev64_opaque__ __ev_srbis( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsrbis") ));
extern __ev64_opaque__ __ev_srbiu( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsrbiu") ));
extern __ev64_opaque__ __ev_srbs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsrbs") ));
extern __ev64_opaque__ __ev_srbu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsrbu") ));
extern __ev64_opaque__ __ev_srhis( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsrhis") ));
extern __ev64_opaque__ __ev_srhiu( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsrhiu") ));
extern __ev64_opaque__ __ev_srhs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsrhs") ));
extern __ev64_opaque__ __ev_srhu( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsrhu") ));
extern __ev64_opaque__ __ev_sris( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsris") ));
extern __ev64_opaque__ __ev_sriu( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsriu") ));
extern __ev64_opaque__ __ev_srois( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsrois") ));
extern __ev64_opaque__ __ev_sroiu( __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2001, 1, "evsroiu") ));
extern __ev64_opaque__ __ev_srs( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsrs") ));
extern __ev64_opaque__ __ev_sru( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsru") ));
extern void __ev_stdb( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstdb") ));
extern void __ev_stdbu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstdbu") ));
extern void __ev_stdbux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstdbux") ));
extern void __ev_stdbx( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstdbx") ));
extern void __ev_stddu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstddu") ));
extern void __ev_stddux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstddux") ));
extern void __ev_stdhu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstdhu") ));
extern void __ev_stdhux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstdhux") ));
extern void __ev_stdwu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstdwu") ));
extern void __ev_stdwux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstdwux") ));
extern void __ev_sthb( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evsthb") ));
extern void __ev_sthbu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evsthbu") ));
extern void __ev_sthbux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evsthbux") ));
extern void __ev_sthbx( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evsthbx") ));
extern void __ev_stwb( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwb") ));
extern void __ev_stwbe( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwbe") ));
extern void __ev_stwbeu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwbeu") ));
extern void __ev_stwbeux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwbeux") ));
extern void __ev_stwbex( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwbex") ));
extern void __ev_stwbo( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwbo") ));
extern void __ev_stwbou( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwbou") ));
extern void __ev_stwboux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwboux") ));
extern void __ev_stwbox( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwbox") ));
extern void __ev_stwbu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwbu") ));
extern void __ev_stwbux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwbux") ));
extern void __ev_stwbx( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwbx") ));
extern void __ev_stwheu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwheu") ));
extern void __ev_stwheux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwheux") ));
extern void __ev_stwhou( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwhou") ));
extern void __ev_stwhoux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwhoux") ));
extern void __ev_stwweu( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwweu") ));
extern void __ev_stwweux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwweux") ));
extern void __ev_stwwou( __ev64_opaque__,  __ev64_opaque__*,  const unsigned int) __attribute__((intrinsic_function(2025, 0, "evstwwou") ));
extern void __ev_stwwoux( __ev64_opaque__,  __ev64_opaque__*,  int) __attribute__((intrinsic_function(2026, 0, "evstwwoux") ));
extern __ev64_opaque__ __ev_subf2add2h( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubf2add2h") ));
extern __ev64_opaque__ __ev_subf2add2hss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubf2add2hss") ));
extern __ev64_opaque__ __ev_subf2add2hus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubf2add2hus") ));
extern __ev64_opaque__ __ev_subfaa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfaa") ));
extern __ev64_opaque__ __ev_subfaddh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddh") ));
extern __ev64_opaque__ __ev_subfaddhss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddhss") ));
extern __ev64_opaque__ __ev_subfaddhus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddhus") ));
extern __ev64_opaque__ __ev_subfaddhx( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddhx") ));
extern __ev64_opaque__ __ev_subfaddhxss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddhxss") ));
extern __ev64_opaque__ __ev_subfaddhxus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddhxus") ));
extern __ev64_opaque__ __ev_subfaddw( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddw") ));
extern __ev64_opaque__ __ev_subfaddwss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddwss") ));
extern __ev64_opaque__ __ev_subfaddwus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddwus") ));
extern __ev64_opaque__ __ev_subfaddwx( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddwx") ));
extern __ev64_opaque__ __ev_subfaddwxss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddwxss") ));
extern __ev64_opaque__ __ev_subfaddwxus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfaddwxus") ));
extern __ev64_opaque__ __ev_subfb( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfb") ));
extern __ev64_opaque__ __ev_subfbss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfbss") ));
extern __ev64_opaque__ __ev_subfbus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfbus") ));
extern __ev64_opaque__ __ev_subfh( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfh") ));
extern __ev64_opaque__ __ev_subfhss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfhss") ));
extern __ev64_opaque__ __ev_subfhus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfhus") ));
extern __ev64_opaque__ __ev_subfhx( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfhx") ));
extern __ev64_opaque__ __ev_subfhxss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfhxss") ));
extern __ev64_opaque__ __ev_subfhxus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfhxus") ));
extern __ev64_opaque__ __ev_subfssiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfssiaa") ));
extern __ev64_opaque__ __ev_subfusiaa( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsubfusiaa") ));
extern __ev64_opaque__ __ev_subfwss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfwss") ));
extern __ev64_opaque__ __ev_subfwus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfwus") ));
extern __ev64_opaque__ __ev_subfwx( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfwx") ));
extern __ev64_opaque__ __ev_subfwxss( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfwxss") ));
extern __ev64_opaque__ __ev_subfwxus( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsubfwxus") ));
extern __ev64_opaque__ __ev_subifb( const unsigned int,  __ev64_opaque__) __attribute__((intrinsic_function(2085, 1, "evsubifb") ));
extern __ev64_opaque__ __ev_subifh( const unsigned int,  __ev64_opaque__) __attribute__((intrinsic_function(2085, 1, "evsubifh") ));
extern __ev64_opaque__ __ev_sum2his( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsum2his") ));
extern __ev64_opaque__ __ev_sum2hisa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum2hisa") ));
extern __ev64_opaque__ __ev_sum2hisaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum2hisaaw") ));
extern __ev64_opaque__ __ev_sum2hiu( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsum2hiu") ));
extern __ev64_opaque__ __ev_sum2hiua( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum2hiua") ));
extern __ev64_opaque__ __ev_sum2hiuaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum2hiuaaw") ));
extern __ev64_opaque__ __ev_sum2hs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsum2hs") ));
extern __ev64_opaque__ __ev_sum2hsa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum2hsa") ));
extern __ev64_opaque__ __ev_sum2hsaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum2hsaaw") ));
extern __ev64_opaque__ __ev_sum2hu( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsum2hu") ));
extern __ev64_opaque__ __ev_sum2hua( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum2hua") ));
extern __ev64_opaque__ __ev_sum2huaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum2huaaw") ));
extern __ev64_opaque__ __ev_sum4bs( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsum4bs") ));
extern __ev64_opaque__ __ev_sum4bsa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum4bsa") ));
extern __ev64_opaque__ __ev_sum4bsaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum4bsaaw") ));
extern __ev64_opaque__ __ev_sum4bu( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsum4bu") ));
extern __ev64_opaque__ __ev_sum4bua( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum4bua") ));
extern __ev64_opaque__ __ev_sum4buaaw( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsum4buaaw") ));
extern __ev64_opaque__ __ev_sumws( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsumws") ));
extern __ev64_opaque__ __ev_sumwsa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsumwsa") ));
extern __ev64_opaque__ __ev_sumwsaa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsumwsaa") ));
extern __ev64_opaque__ __ev_sumwu( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evsumwu") ));
extern __ev64_opaque__ __ev_sumwua( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsumwua") ));
extern __ev64_opaque__ __ev_sumwuaa( __ev64_opaque__) __attribute__((intrinsic_function(2000, 0, "evsumwuaa") ));
extern __ev64_opaque__ __ev_swapbhilo( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evswapbhilo") ));
extern __ev64_opaque__ __ev_swapblohi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evswapblohi") ));
extern __ev64_opaque__ __ev_swaphe( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evswaphe") ));
extern __ev64_opaque__ __ev_swaphhi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evswaphhi") ));
extern __ev64_opaque__ __ev_swaphhilo( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evswaphhilo") ));
extern __ev64_opaque__ __ev_swaphlo( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evswaphlo") ));
extern __ev64_opaque__ __ev_swaphlohi( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evswaphlohi") ));
extern __ev64_opaque__ __ev_swapho( __ev64_opaque__,  __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evswapho") ));
extern __ev64_opaque__ __ev_unpkhibsi( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpkhibsi") ));
extern __ev64_opaque__ __ev_unpkhibui( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpkhibui") ));
extern __ev64_opaque__ __ev_unpkhihf( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpkhihf") ));
extern __ev64_opaque__ __ev_unpkhihsi( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpkhihsi") ));
extern __ev64_opaque__ __ev_unpkhihui( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpkhihui") ));
extern __ev64_opaque__ __ev_unpklobsi( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpklobsi") ));
extern __ev64_opaque__ __ev_unpklobui( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpklobui") ));
extern __ev64_opaque__ __ev_unpklohf( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpklohf") ));
extern __ev64_opaque__ __ev_unpklohsi( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpklohsi") ));
extern __ev64_opaque__ __ev_unpklohui( __ev64_opaque__) __attribute__((intrinsic_pseudo(1, "evunpklohui") ));
extern __ev64_opaque__ __ev_xtrb( __ev64_opaque__,  const unsigned int,  const unsigned int) __attribute__((intrinsic_function(2087, 1, "evxtrb") ));
extern __ev64_opaque__ __ev_xtrd( __ev64_opaque__,  __ev64_opaque__,  const unsigned int) __attribute__((intrinsic_function(2084, 1, "evxtrd") ));
extern __ev64_opaque__ __ev_xtrh( __ev64_opaque__,  const unsigned int,  const unsigned int) __attribute__((intrinsic_function(2087, 1, "evxtrh") ));
