/*************************************************************************************************
*
* This file is generated by Main_Define_FIX_X_Y_Types.m.  Changes should be made there.
*
* Filename:    t_fix_x_y.h
*
* Description: Defines fixed point scaling types w/o unit association in cdf-file.
*
* Forward Engine Management Systems
*
* Copyright 1999-2011, Delphi Technologies, Inc.
* All rights reserved.
*
**************************************************************************************************
*
* Current Module Info:
* %full_name:     kok_pt2#1/incl/t_fix_x_y.h/2 %
* %date_created:  Fri Jun 17 15:12:35 2011 %
* %version:       2 %
* %derived_by:    tzzpjy %
*
*************************************************************************************************/
 
 
#ifndef T_FIX_X_Y_H
#define T_FIX_X_Y_H


/**********************************************************************************
 *                                   8bit Signed                                  *
 **********************************************************************************/

/* power-of-two range: [-32768 , 32512] , Res = 256 */
typedef signed char            T_FIX_S8_n08;
#define V_FIX_S8_n08(val)      (signed char)((double)(((double)val)*0.00390625))
#define S_FIX_S8_n08           -8

/* power-of-two range: [-16384 , 16256] , Res = 128 */
typedef signed char            T_FIX_S8_n07;
#define V_FIX_S8_n07(val)      (signed char)((double)(((double)val)*0.0078125))
#define S_FIX_S8_n07           -7

/* power-of-two range: [-8192 , 8128] , Res = 64 */
typedef signed char            T_FIX_S8_n06;
#define V_FIX_S8_n06(val)      (signed char)((double)(((double)val)*0.015625))
#define S_FIX_S8_n06           -6

/* power-of-two range: [-4096 , 4064] , Res = 32 */
typedef signed char            T_FIX_S8_n05;
#define V_FIX_S8_n05(val)      (signed char)((double)(((double)val)*0.03125))
#define S_FIX_S8_n05           -5

/* power-of-two range: [-2048 , 2032] , Res = 16 */
typedef signed char            T_FIX_S8_n04;
#define V_FIX_S8_n04(val)      (signed char)((double)(((double)val)*0.0625))
#define S_FIX_S8_n04           -4

/* power-of-two range: [-1024 , 1016] , Res = 8 */
typedef signed char            T_FIX_S8_n03;
#define V_FIX_S8_n03(val)      (signed char)((double)(((double)val)*0.125))
#define S_FIX_S8_n03           -3

/* power-of-two range: [-512 , 508] , Res = 4 */
typedef signed char            T_FIX_S8_n02;
#define V_FIX_S8_n02(val)      (signed char)((double)(((double)val)*0.25))
#define S_FIX_S8_n02           -2

/* power-of-two range: [-256 , 254] , Res = 2 */
typedef signed char            T_FIX_S8_n01;
#define V_FIX_S8_n01(val)      (signed char)((double)(((double)val)*0.5))
#define S_FIX_S8_n01           -1

/* power-of-two range: [-128 , 127] , Res = 1 */
typedef signed char            T_FIX_S8_00;
#define V_FIX_S8_00(val)       (signed char)((double)(((double)val)*1))
#define S_FIX_S8_00            0

/* power-of-two range: [-64 , 63.5] , Res = 0.5 */
typedef signed char            T_FIX_S8_01;
#define V_FIX_S8_01(val)       (signed char)((double)(((double)val)*2))
#define S_FIX_S8_01            1

/* power-of-two range: [-32 , 31.75] , Res = 0.25 */
typedef signed char            T_FIX_S8_02;
#define V_FIX_S8_02(val)       (signed char)((double)(((double)val)*4))
#define S_FIX_S8_02            2

/* power-of-two range: [-16 , 15.875] , Res = 0.125 */
typedef signed char            T_FIX_S8_03;
#define V_FIX_S8_03(val)       (signed char)((double)(((double)val)*8))
#define S_FIX_S8_03            3

/* power-of-two range: [-8 , 7.9375] , Res = 0.0625 */
typedef signed char            T_FIX_S8_04;
#define V_FIX_S8_04(val)       (signed char)((double)(((double)val)*16))
#define S_FIX_S8_04            4

/* power-of-two range: [-4 , 3.96875] , Res = 0.03125 */
typedef signed char            T_FIX_S8_05;
#define V_FIX_S8_05(val)       (signed char)((double)(((double)val)*32))
#define S_FIX_S8_05            5

/* power-of-two range: [-2 , 1.984375] , Res = 0.015625 */
typedef signed char            T_FIX_S8_06;
#define V_FIX_S8_06(val)       (signed char)((double)(((double)val)*64))
#define S_FIX_S8_06            6

/* power-of-two range: [-1 , 0.9921875] , Res = 0.0078125 */
typedef signed char            T_FIX_S8_07;
#define V_FIX_S8_07(val)       (signed char)((double)(((double)val)*128))
#define S_FIX_S8_07            7

/* power-of-two range: [-0.5 , 0.49609375] , Res = 0.00390625 */
typedef signed char            T_FIX_S8_08;
#define V_FIX_S8_08(val)       (signed char)((double)(((double)val)*256))
#define S_FIX_S8_08            8

/* power-of-two range: [-0.25 , 0.248046875] , Res = 0.001953125 */
typedef signed char            T_FIX_S8_09;
#define V_FIX_S8_09(val)       (signed char)((double)(((double)val)*512))
#define S_FIX_S8_09            9

/* power-of-two range: [-0.125 , 0.1240234375] , Res = 0.0009765625 */
typedef signed char            T_FIX_S8_10;
#define V_FIX_S8_10(val)       (signed char)((double)(((double)val)*1024))
#define S_FIX_S8_10            10

/* power-of-two range: [-0.0625 , 0.06201171875] , Res = 0.00048828125 */
typedef signed char            T_FIX_S8_11;
#define V_FIX_S8_11(val)       (signed char)((double)(((double)val)*2048))
#define S_FIX_S8_11            11

/* power-of-two range: [-0.03125 , 0.031005859375] , Res = 0.000244140625 */
typedef signed char            T_FIX_S8_12;
#define V_FIX_S8_12(val)       (signed char)((double)(((double)val)*4096))
#define S_FIX_S8_12            12

/* power-of-two range: [-0.015625 , 0.0155029296875] , Res = 0.0001220703125 */
typedef signed char            T_FIX_S8_13;
#define V_FIX_S8_13(val)       (signed char)((double)(((double)val)*8192))
#define S_FIX_S8_13            13

/* power-of-two range: [-0.0078125 , 0.00775146484375] , Res = 6.103515625e-005 */
typedef signed char            T_FIX_S8_14;
#define V_FIX_S8_14(val)       (signed char)((double)(((double)val)*16384))
#define S_FIX_S8_14            14

/* power-of-two range: [-0.00390625 , 0.003875732421875] , Res = 3.0517578125e-005 */
typedef signed char            T_FIX_S8_15;
#define V_FIX_S8_15(val)       (signed char)((double)(((double)val)*32768))
#define S_FIX_S8_15            15

/* power-of-two range: [-0.001953125 , 0.0019378662109375] , Res = 1.52587890625e-005 */
typedef signed char            T_FIX_S8_16;
#define V_FIX_S8_16(val)       (signed char)((double)(((double)val)*65536))
#define S_FIX_S8_16            16



/**********************************************************************************
 *                                   8bit Unsigned                                *
 **********************************************************************************/

/* power-of-two range: [0 , 65280] , Res = 256 */
typedef unsigned char          T_FIX_U8_n08;
#define V_FIX_U8_n08(val)      (unsigned char)((double)(((double)val)*0.00390625))
#define S_FIX_U8_n08           -8

/* power-of-two range: [0 , 32640] , Res = 128 */
typedef unsigned char          T_FIX_U8_n07;
#define V_FIX_U8_n07(val)      (unsigned char)((double)(((double)val)*0.0078125))
#define S_FIX_U8_n07           -7

/* power-of-two range: [0 , 16320] , Res = 64 */
typedef unsigned char          T_FIX_U8_n06;
#define V_FIX_U8_n06(val)      (unsigned char)((double)(((double)val)*0.015625))
#define S_FIX_U8_n06           -6

/* power-of-two range: [0 , 8160] , Res = 32 */
typedef unsigned char          T_FIX_U8_n05;
#define V_FIX_U8_n05(val)      (unsigned char)((double)(((double)val)*0.03125))
#define S_FIX_U8_n05           -5

/* power-of-two range: [0 , 4080] , Res = 16 */
typedef unsigned char          T_FIX_U8_n04;
#define V_FIX_U8_n04(val)      (unsigned char)((double)(((double)val)*0.0625))
#define S_FIX_U8_n04           -4

/* power-of-two range: [0 , 2040] , Res = 8 */
typedef unsigned char          T_FIX_U8_n03;
#define V_FIX_U8_n03(val)      (unsigned char)((double)(((double)val)*0.125))
#define S_FIX_U8_n03           -3

/* power-of-two range: [0 , 1020] , Res = 4 */
typedef unsigned char          T_FIX_U8_n02;
#define V_FIX_U8_n02(val)      (unsigned char)((double)(((double)val)*0.25))
#define S_FIX_U8_n02           -2

/* power-of-two range: [0 , 510] , Res = 2 */
typedef unsigned char          T_FIX_U8_n01;
#define V_FIX_U8_n01(val)      (unsigned char)((double)(((double)val)*0.5))
#define S_FIX_U8_n01           -1

/* power-of-two range: [0 , 255] , Res = 1 */
typedef unsigned char          T_FIX_U8_00;
#define V_FIX_U8_00(val)       (unsigned char)((double)(((double)val)*1))
#define S_FIX_U8_00            0

/* power-of-two range: [0 , 127.5] , Res = 0.5 */
typedef unsigned char          T_FIX_U8_01;
#define V_FIX_U8_01(val)       (unsigned char)((double)(((double)val)*2))
#define S_FIX_U8_01            1

/* power-of-two range: [0 , 63.75] , Res = 0.25 */
typedef unsigned char          T_FIX_U8_02;
#define V_FIX_U8_02(val)       (unsigned char)((double)(((double)val)*4))
#define S_FIX_U8_02            2

/* power-of-two range: [0 , 31.875] , Res = 0.125 */
typedef unsigned char          T_FIX_U8_03;
#define V_FIX_U8_03(val)       (unsigned char)((double)(((double)val)*8))
#define S_FIX_U8_03            3

/* power-of-two range: [0 , 15.9375] , Res = 0.0625 */
typedef unsigned char          T_FIX_U8_04;
#define V_FIX_U8_04(val)       (unsigned char)((double)(((double)val)*16))
#define S_FIX_U8_04            4

/* power-of-two range: [0 , 7.96875] , Res = 0.03125 */
typedef unsigned char          T_FIX_U8_05;
#define V_FIX_U8_05(val)       (unsigned char)((double)(((double)val)*32))
#define S_FIX_U8_05            5

/* power-of-two range: [0 , 3.984375] , Res = 0.015625 */
typedef unsigned char          T_FIX_U8_06;
#define V_FIX_U8_06(val)       (unsigned char)((double)(((double)val)*64))
#define S_FIX_U8_06            6

/* power-of-two range: [0 , 1.9921875] , Res = 0.0078125 */
typedef unsigned char          T_FIX_U8_07;
#define V_FIX_U8_07(val)       (unsigned char)((double)(((double)val)*128))
#define S_FIX_U8_07            7

/* power-of-two range: [0 , 0.99609375] , Res = 0.00390625 */
typedef unsigned char          T_FIX_U8_08;
#define V_FIX_U8_08(val)       (unsigned char)((double)(((double)val)*256))
#define S_FIX_U8_08            8

/* power-of-two range: [0 , 0.498046875] , Res = 0.001953125 */
typedef unsigned char          T_FIX_U8_09;
#define V_FIX_U8_09(val)       (unsigned char)((double)(((double)val)*512))
#define S_FIX_U8_09            9

/* power-of-two range: [0 , 0.2490234375] , Res = 0.0009765625 */
typedef unsigned char          T_FIX_U8_10;
#define V_FIX_U8_10(val)       (unsigned char)((double)(((double)val)*1024))
#define S_FIX_U8_10            10

/* power-of-two range: [0 , 0.12451171875] , Res = 0.00048828125 */
typedef unsigned char          T_FIX_U8_11;
#define V_FIX_U8_11(val)       (unsigned char)((double)(((double)val)*2048))
#define S_FIX_U8_11            11

/* power-of-two range: [0 , 0.062255859375] , Res = 0.000244140625 */
typedef unsigned char          T_FIX_U8_12;
#define V_FIX_U8_12(val)       (unsigned char)((double)(((double)val)*4096))
#define S_FIX_U8_12            12

/* power-of-two range: [0 , 0.0311279296875] , Res = 0.0001220703125 */
typedef unsigned char          T_FIX_U8_13;
#define V_FIX_U8_13(val)       (unsigned char)((double)(((double)val)*8192))
#define S_FIX_U8_13            13

/* power-of-two range: [0 , 0.01556396484375] , Res = 6.103515625e-005 */
typedef unsigned char          T_FIX_U8_14;
#define V_FIX_U8_14(val)       (unsigned char)((double)(((double)val)*16384))
#define S_FIX_U8_14            14

/* power-of-two range: [0 , 0.007781982421875] , Res = 3.0517578125e-005 */
typedef unsigned char          T_FIX_U8_15;
#define V_FIX_U8_15(val)       (unsigned char)((double)(((double)val)*32768))
#define S_FIX_U8_15            15

/* power-of-two range: [0 , 0.0038909912109375] , Res = 1.52587890625e-005 */
typedef unsigned char          T_FIX_U8_16;
#define V_FIX_U8_16(val)       (unsigned char)((double)(((double)val)*65536))
#define S_FIX_U8_16            16



/**********************************************************************************
 *                                   16bit Signed                                 *
 **********************************************************************************/

/* power-of-two range: [-8388608 , 8388352] , Res = 256 */
typedef short signed int       T_FIX_S16_n08;
#define V_FIX_S16_n08(val)     (short signed int)((double)(((double)val)*0.00390625))
#define S_FIX_S16_n08          -8

/* power-of-two range: [-4194304 , 4194176] , Res = 128 */
typedef short signed int       T_FIX_S16_n07;
#define V_FIX_S16_n07(val)     (short signed int)((double)(((double)val)*0.0078125))
#define S_FIX_S16_n07          -7

/* power-of-two range: [-2097152 , 2097088] , Res = 64 */
typedef short signed int       T_FIX_S16_n06;
#define V_FIX_S16_n06(val)     (short signed int)((double)(((double)val)*0.015625))
#define S_FIX_S16_n06          -6

/* power-of-two range: [-1048576 , 1048544] , Res = 32 */
typedef short signed int       T_FIX_S16_n05;
#define V_FIX_S16_n05(val)     (short signed int)((double)(((double)val)*0.03125))
#define S_FIX_S16_n05          -5

/* power-of-two range: [-524288 , 524272] , Res = 16 */
typedef short signed int       T_FIX_S16_n04;
#define V_FIX_S16_n04(val)     (short signed int)((double)(((double)val)*0.0625))
#define S_FIX_S16_n04          -4

/* power-of-two range: [-262144 , 262136] , Res = 8 */
typedef short signed int       T_FIX_S16_n03;
#define V_FIX_S16_n03(val)     (short signed int)((double)(((double)val)*0.125))
#define S_FIX_S16_n03          -3

/* power-of-two range: [-131072 , 131068] , Res = 4 */
typedef short signed int       T_FIX_S16_n02;
#define V_FIX_S16_n02(val)     (short signed int)((double)(((double)val)*0.25))
#define S_FIX_S16_n02          -2

/* power-of-two range: [-65536 , 65534] , Res = 2 */
typedef short signed int       T_FIX_S16_n01;
#define V_FIX_S16_n01(val)     (short signed int)((double)(((double)val)*0.5))
#define S_FIX_S16_n01          -1

/* power-of-two range: [-32768 , 32767] , Res = 1 */
typedef short signed int       T_FIX_S16_00;
#define V_FIX_S16_00(val)      (short signed int)((double)(((double)val)*1))
#define S_FIX_S16_00           0

/* power-of-two range: [-16384 , 16383.5] , Res = 0.5 */
typedef short signed int       T_FIX_S16_01;
#define V_FIX_S16_01(val)      (short signed int)((double)(((double)val)*2))
#define S_FIX_S16_01           1

/* power-of-two range: [-8192 , 8191.75] , Res = 0.25 */
typedef short signed int       T_FIX_S16_02;
#define V_FIX_S16_02(val)      (short signed int)((double)(((double)val)*4))
#define S_FIX_S16_02           2

/* power-of-two range: [-4096 , 4095.875] , Res = 0.125 */
typedef short signed int       T_FIX_S16_03;
#define V_FIX_S16_03(val)      (short signed int)((double)(((double)val)*8))
#define S_FIX_S16_03           3

/* power-of-two range: [-2048 , 2047.9375] , Res = 0.0625 */
typedef short signed int       T_FIX_S16_04;
#define V_FIX_S16_04(val)      (short signed int)((double)(((double)val)*16))
#define S_FIX_S16_04           4

/* power-of-two range: [-1024 , 1023.96875] , Res = 0.03125 */
typedef short signed int       T_FIX_S16_05;
#define V_FIX_S16_05(val)      (short signed int)((double)(((double)val)*32))
#define S_FIX_S16_05           5

/* power-of-two range: [-512 , 511.984375] , Res = 0.015625 */
typedef short signed int       T_FIX_S16_06;
#define V_FIX_S16_06(val)      (short signed int)((double)(((double)val)*64))
#define S_FIX_S16_06           6

/* power-of-two range: [-256 , 255.9921875] , Res = 0.0078125 */
typedef short signed int       T_FIX_S16_07;
#define V_FIX_S16_07(val)      (short signed int)((double)(((double)val)*128))
#define S_FIX_S16_07           7

/* power-of-two range: [-128 , 127.99609375] , Res = 0.00390625 */
typedef short signed int       T_FIX_S16_08;
#define V_FIX_S16_08(val)      (short signed int)((double)(((double)val)*256))
#define S_FIX_S16_08           8

/* power-of-two range: [-64 , 63.998046875] , Res = 0.001953125 */
typedef short signed int       T_FIX_S16_09;
#define V_FIX_S16_09(val)      (short signed int)((double)(((double)val)*512))
#define S_FIX_S16_09           9

/* power-of-two range: [-32 , 31.9990234375] , Res = 0.0009765625 */
typedef short signed int       T_FIX_S16_10;
#define V_FIX_S16_10(val)      (short signed int)((double)(((double)val)*1024))
#define S_FIX_S16_10           10

/* power-of-two range: [-16 , 15.99951171875] , Res = 0.00048828125 */
typedef short signed int       T_FIX_S16_11;
#define V_FIX_S16_11(val)      (short signed int)((double)(((double)val)*2048))
#define S_FIX_S16_11           11

/* power-of-two range: [-8 , 7.999755859375] , Res = 0.000244140625 */
typedef short signed int       T_FIX_S16_12;
#define V_FIX_S16_12(val)      (short signed int)((double)(((double)val)*4096))
#define S_FIX_S16_12           12

/* power-of-two range: [-4 , 3.9998779296875] , Res = 0.0001220703125 */
typedef short signed int       T_FIX_S16_13;
#define V_FIX_S16_13(val)      (short signed int)((double)(((double)val)*8192))
#define S_FIX_S16_13           13

/* power-of-two range: [-2 , 1.99993896484375] , Res = 6.103515625e-005 */
typedef short signed int       T_FIX_S16_14;
#define V_FIX_S16_14(val)      (short signed int)((double)(((double)val)*16384))
#define S_FIX_S16_14           14

/* power-of-two range: [-1 , 0.999969482421875] , Res = 3.0517578125e-005 */
typedef short signed int       T_FIX_S16_15;
#define V_FIX_S16_15(val)      (short signed int)((double)(((double)val)*32768))
#define S_FIX_S16_15           15

/* power-of-two range: [-0.5 , 0.4999847412109375] , Res = 1.52587890625e-005 */
typedef short signed int       T_FIX_S16_16;
#define V_FIX_S16_16(val)      (short signed int)((double)(((double)val)*65536))
#define S_FIX_S16_16           16

/* power-of-two range: [-0.25 , 0.24999237060546875] , Res = 7.62939453125e-006 */
typedef short signed int       T_FIX_S16_17;
#define V_FIX_S16_17(val)      (short signed int)((double)(((double)val)*131072))
#define S_FIX_S16_17           17

/* power-of-two range: [-0.125 , 0.12499618530273438] , Res = 3.814697265625e-006 */
typedef short signed int       T_FIX_S16_18;
#define V_FIX_S16_18(val)      (short signed int)((double)(((double)val)*262144))
#define S_FIX_S16_18           18

/* power-of-two range: [-0.0625 , 0.062498092651367188] , Res = 1.9073486328125e-006 */
typedef short signed int       T_FIX_S16_19;
#define V_FIX_S16_19(val)      (short signed int)((double)(((double)val)*524288))
#define S_FIX_S16_19           19

/* power-of-two range: [-0.03125 , 0.031249046325683594] , Res = 9.5367431640625e-007 */
typedef short signed int       T_FIX_S16_20;
#define V_FIX_S16_20(val)      (short signed int)((double)(((double)val)*1048576))
#define S_FIX_S16_20           20

/* power-of-two range: [-0.015625 , 0.015624523162841797] , Res = 4.76837158203125e-007 */
typedef short signed int       T_FIX_S16_21;
#define V_FIX_S16_21(val)      (short signed int)((double)(((double)val)*2097152))
#define S_FIX_S16_21           21

/* power-of-two range: [-0.0078125 , 0.0078122615814208984] , Res = 2.384185791015625e-007 */
typedef short signed int       T_FIX_S16_22;
#define V_FIX_S16_22(val)      (short signed int)((double)(((double)val)*4194304))
#define S_FIX_S16_22           22

/* power-of-two range: [-0.00390625 , 0.0039061307907104492] , Res = 1.1920928955078125e-007 */
typedef short signed int       T_FIX_S16_23;
#define V_FIX_S16_23(val)      (short signed int)((double)(((double)val)*8388608))
#define S_FIX_S16_23           23

/* power-of-two range: [-0.001953125 , 0.0019530653953552246] , Res = 5.9604644775390625e-008 */
typedef short signed int       T_FIX_S16_24;
#define V_FIX_S16_24(val)      (short signed int)((double)(((double)val)*16777216))
#define S_FIX_S16_24           24



/**********************************************************************************
 *                                   16bit Unsigned                               *
 **********************************************************************************/

/* power-of-two range: [0 , 16776960] , Res = 256 */
typedef short unsigned int     T_FIX_U16_n08;
#define V_FIX_U16_n08(val)     (short unsigned int)((double)(((double)val)*0.00390625))
#define S_FIX_U16_n08          -8

/* power-of-two range: [0 , 8388480] , Res = 128 */
typedef short unsigned int     T_FIX_U16_n07;
#define V_FIX_U16_n07(val)     (short unsigned int)((double)(((double)val)*0.0078125))
#define S_FIX_U16_n07          -7

/* power-of-two range: [0 , 4194240] , Res = 64 */
typedef short unsigned int     T_FIX_U16_n06;
#define V_FIX_U16_n06(val)     (short unsigned int)((double)(((double)val)*0.015625))
#define S_FIX_U16_n06          -6

/* power-of-two range: [0 , 2097120] , Res = 32 */
typedef short unsigned int     T_FIX_U16_n05;
#define V_FIX_U16_n05(val)     (short unsigned int)((double)(((double)val)*0.03125))
#define S_FIX_U16_n05          -5

/* power-of-two range: [0 , 1048560] , Res = 16 */
typedef short unsigned int     T_FIX_U16_n04;
#define V_FIX_U16_n04(val)     (short unsigned int)((double)(((double)val)*0.0625))
#define S_FIX_U16_n04          -4

/* power-of-two range: [0 , 524280] , Res = 8 */
typedef short unsigned int     T_FIX_U16_n03;
#define V_FIX_U16_n03(val)     (short unsigned int)((double)(((double)val)*0.125))
#define S_FIX_U16_n03          -3

/* power-of-two range: [0 , 262140] , Res = 4 */
typedef short unsigned int     T_FIX_U16_n02;
#define V_FIX_U16_n02(val)     (short unsigned int)((double)(((double)val)*0.25))
#define S_FIX_U16_n02          -2

/* power-of-two range: [0 , 131070] , Res = 2 */
typedef short unsigned int     T_FIX_U16_n01;
#define V_FIX_U16_n01(val)     (short unsigned int)((double)(((double)val)*0.5))
#define S_FIX_U16_n01          -1

/* power-of-two range: [0 , 65535] , Res = 1 */
typedef short unsigned int     T_FIX_U16_00;
#define V_FIX_U16_00(val)      (short unsigned int)((double)(((double)val)*1))
#define S_FIX_U16_00           0

/* power-of-two range: [0 , 32767.5] , Res = 0.5 */
typedef short unsigned int     T_FIX_U16_01;
#define V_FIX_U16_01(val)      (short unsigned int)((double)(((double)val)*2))
#define S_FIX_U16_01           1

/* power-of-two range: [0 , 16383.75] , Res = 0.25 */
typedef short unsigned int     T_FIX_U16_02;
#define V_FIX_U16_02(val)      (short unsigned int)((double)(((double)val)*4))
#define S_FIX_U16_02           2

/* power-of-two range: [0 , 8191.875] , Res = 0.125 */
typedef short unsigned int     T_FIX_U16_03;
#define V_FIX_U16_03(val)      (short unsigned int)((double)(((double)val)*8))
#define S_FIX_U16_03           3

/* power-of-two range: [0 , 4095.9375] , Res = 0.0625 */
typedef short unsigned int     T_FIX_U16_04;
#define V_FIX_U16_04(val)      (short unsigned int)((double)(((double)val)*16))
#define S_FIX_U16_04           4

/* power-of-two range: [0 , 2047.96875] , Res = 0.03125 */
typedef short unsigned int     T_FIX_U16_05;
#define V_FIX_U16_05(val)      (short unsigned int)((double)(((double)val)*32))
#define S_FIX_U16_05           5

/* power-of-two range: [0 , 1023.984375] , Res = 0.015625 */
typedef short unsigned int     T_FIX_U16_06;
#define V_FIX_U16_06(val)      (short unsigned int)((double)(((double)val)*64))
#define S_FIX_U16_06           6

/* power-of-two range: [0 , 511.9921875] , Res = 0.0078125 */
typedef short unsigned int     T_FIX_U16_07;
#define V_FIX_U16_07(val)      (short unsigned int)((double)(((double)val)*128))
#define S_FIX_U16_07           7

/* power-of-two range: [0 , 255.99609375] , Res = 0.00390625 */
typedef short unsigned int     T_FIX_U16_08;
#define V_FIX_U16_08(val)      (short unsigned int)((double)(((double)val)*256))
#define S_FIX_U16_08           8

/* power-of-two range: [0 , 127.998046875] , Res = 0.001953125 */
typedef short unsigned int     T_FIX_U16_09;
#define V_FIX_U16_09(val)      (short unsigned int)((double)(((double)val)*512))
#define S_FIX_U16_09           9

/* power-of-two range: [0 , 63.9990234375] , Res = 0.0009765625 */
typedef short unsigned int     T_FIX_U16_10;
#define V_FIX_U16_10(val)      (short unsigned int)((double)(((double)val)*1024))
#define S_FIX_U16_10           10

/* power-of-two range: [0 , 31.99951171875] , Res = 0.00048828125 */
typedef short unsigned int     T_FIX_U16_11;
#define V_FIX_U16_11(val)      (short unsigned int)((double)(((double)val)*2048))
#define S_FIX_U16_11           11

/* power-of-two range: [0 , 15.999755859375] , Res = 0.000244140625 */
typedef short unsigned int     T_FIX_U16_12;
#define V_FIX_U16_12(val)      (short unsigned int)((double)(((double)val)*4096))
#define S_FIX_U16_12           12

/* power-of-two range: [0 , 7.9998779296875] , Res = 0.0001220703125 */
typedef short unsigned int     T_FIX_U16_13;
#define V_FIX_U16_13(val)      (short unsigned int)((double)(((double)val)*8192))
#define S_FIX_U16_13           13

/* power-of-two range: [0 , 3.99993896484375] , Res = 6.103515625e-005 */
typedef short unsigned int     T_FIX_U16_14;
#define V_FIX_U16_14(val)      (short unsigned int)((double)(((double)val)*16384))
#define S_FIX_U16_14           14

/* power-of-two range: [0 , 1.999969482421875] , Res = 3.0517578125e-005 */
typedef short unsigned int     T_FIX_U16_15;
#define V_FIX_U16_15(val)      (short unsigned int)((double)(((double)val)*32768))
#define S_FIX_U16_15           15

/* power-of-two range: [0 , 0.9999847412109375] , Res = 1.52587890625e-005 */
typedef short unsigned int     T_FIX_U16_16;
#define V_FIX_U16_16(val)      (short unsigned int)((double)(((double)val)*65536))
#define S_FIX_U16_16           16

/* power-of-two range: [0 , 0.49999237060546875] , Res = 7.62939453125e-006 */
typedef short unsigned int     T_FIX_U16_17;
#define V_FIX_U16_17(val)      (short unsigned int)((double)(((double)val)*131072))
#define S_FIX_U16_17           17

/* power-of-two range: [0 , 0.24999618530273438] , Res = 3.814697265625e-006 */
typedef short unsigned int     T_FIX_U16_18;
#define V_FIX_U16_18(val)      (short unsigned int)((double)(((double)val)*262144))
#define S_FIX_U16_18           18

/* power-of-two range: [0 , 0.12499809265136719] , Res = 1.9073486328125e-006 */
typedef short unsigned int     T_FIX_U16_19;
#define V_FIX_U16_19(val)      (short unsigned int)((double)(((double)val)*524288))
#define S_FIX_U16_19           19

/* power-of-two range: [0 , 0.062499046325683594] , Res = 9.5367431640625e-007 */
typedef short unsigned int     T_FIX_U16_20;
#define V_FIX_U16_20(val)      (short unsigned int)((double)(((double)val)*1048576))
#define S_FIX_U16_20           20

/* power-of-two range: [0 , 0.031249523162841797] , Res = 4.76837158203125e-007 */
typedef short unsigned int     T_FIX_U16_21;
#define V_FIX_U16_21(val)      (short unsigned int)((double)(((double)val)*2097152))
#define S_FIX_U16_21           21

/* power-of-two range: [0 , 0.015624761581420898] , Res = 2.384185791015625e-007 */
typedef short unsigned int     T_FIX_U16_22;
#define V_FIX_U16_22(val)      (short unsigned int)((double)(((double)val)*4194304))
#define S_FIX_U16_22           22

/* power-of-two range: [0 , 0.0078123807907104492] , Res = 1.1920928955078125e-007 */
typedef short unsigned int     T_FIX_U16_23;
#define V_FIX_U16_23(val)      (short unsigned int)((double)(((double)val)*8388608))
#define S_FIX_U16_23           23

/* power-of-two range: [0 , 0.0039061903953552246] , Res = 5.9604644775390625e-008 */
typedef short unsigned int     T_FIX_U16_24;
#define V_FIX_U16_24(val)      (short unsigned int)((double)(((double)val)*16777216))
#define S_FIX_U16_24           24



/**********************************************************************************
 *                                   32bit Signed                                 *
 **********************************************************************************/

/* power-of-two range: [-549755813888 , 549755813632] , Res = 256 */
typedef long signed int        T_FIX_S32_n08;
#define V_FIX_S32_n08(val)     (long signed int)((double)(((double)val)*0.00390625))
#define S_FIX_S32_n08          -8

/* power-of-two range: [-274877906944 , 274877906816] , Res = 128 */
typedef long signed int        T_FIX_S32_n07;
#define V_FIX_S32_n07(val)     (long signed int)((double)(((double)val)*0.0078125))
#define S_FIX_S32_n07          -7

/* power-of-two range: [-137438953472 , 137438953408] , Res = 64 */
typedef long signed int        T_FIX_S32_n06;
#define V_FIX_S32_n06(val)     (long signed int)((double)(((double)val)*0.015625))
#define S_FIX_S32_n06          -6

/* power-of-two range: [-68719476736 , 68719476704] , Res = 32 */
typedef long signed int        T_FIX_S32_n05;
#define V_FIX_S32_n05(val)     (long signed int)((double)(((double)val)*0.03125))
#define S_FIX_S32_n05          -5

/* power-of-two range: [-34359738368 , 34359738352] , Res = 16 */
typedef long signed int        T_FIX_S32_n04;
#define V_FIX_S32_n04(val)     (long signed int)((double)(((double)val)*0.0625))
#define S_FIX_S32_n04          -4

/* power-of-two range: [-17179869184 , 17179869176] , Res = 8 */
typedef long signed int        T_FIX_S32_n03;
#define V_FIX_S32_n03(val)     (long signed int)((double)(((double)val)*0.125))
#define S_FIX_S32_n03          -3

/* power-of-two range: [-8589934592 , 8589934588] , Res = 4 */
typedef long signed int        T_FIX_S32_n02;
#define V_FIX_S32_n02(val)     (long signed int)((double)(((double)val)*0.25))
#define S_FIX_S32_n02          -2

/* power-of-two range: [-4294967296 , 4294967294] , Res = 2 */
typedef long signed int        T_FIX_S32_n01;
#define V_FIX_S32_n01(val)     (long signed int)((double)(((double)val)*0.5))
#define S_FIX_S32_n01          -1

/* power-of-two range: [-2147483648 , 2147483647] , Res = 1 */
typedef long signed int        T_FIX_S32_00;
#define V_FIX_S32_00(val)      (long signed int)((double)(((double)val)*1))
#define S_FIX_S32_00           0

/* power-of-two range: [-1073741824 , 1073741823.5] , Res = 0.5 */
typedef long signed int        T_FIX_S32_01;
#define V_FIX_S32_01(val)      (long signed int)((double)(((double)val)*2))
#define S_FIX_S32_01           1

/* power-of-two range: [-536870912 , 536870911.75] , Res = 0.25 */
typedef long signed int        T_FIX_S32_02;
#define V_FIX_S32_02(val)      (long signed int)((double)(((double)val)*4))
#define S_FIX_S32_02           2

/* power-of-two range: [-268435456 , 268435455.875] , Res = 0.125 */
typedef long signed int        T_FIX_S32_03;
#define V_FIX_S32_03(val)      (long signed int)((double)(((double)val)*8))
#define S_FIX_S32_03           3

/* power-of-two range: [-134217728 , 134217727.9375] , Res = 0.0625 */
typedef long signed int        T_FIX_S32_04;
#define V_FIX_S32_04(val)      (long signed int)((double)(((double)val)*16))
#define S_FIX_S32_04           4

/* power-of-two range: [-67108864 , 67108863.96875] , Res = 0.03125 */
typedef long signed int        T_FIX_S32_05;
#define V_FIX_S32_05(val)      (long signed int)((double)(((double)val)*32))
#define S_FIX_S32_05           5

/* power-of-two range: [-33554432 , 33554431.984375] , Res = 0.015625 */
typedef long signed int        T_FIX_S32_06;
#define V_FIX_S32_06(val)      (long signed int)((double)(((double)val)*64))
#define S_FIX_S32_06           6

/* power-of-two range: [-16777216 , 16777215.9921875] , Res = 0.0078125 */
typedef long signed int        T_FIX_S32_07;
#define V_FIX_S32_07(val)      (long signed int)((double)(((double)val)*128))
#define S_FIX_S32_07           7

/* power-of-two range: [-8388608 , 8388607.99609375] , Res = 0.00390625 */
typedef long signed int        T_FIX_S32_08;
#define V_FIX_S32_08(val)      (long signed int)((double)(((double)val)*256))
#define S_FIX_S32_08           8

/* power-of-two range: [-4194304 , 4194303.998046875] , Res = 0.001953125 */
typedef long signed int        T_FIX_S32_09;
#define V_FIX_S32_09(val)      (long signed int)((double)(((double)val)*512))
#define S_FIX_S32_09           9

/* power-of-two range: [-2097152 , 2097151.9990234375] , Res = 0.0009765625 */
typedef long signed int        T_FIX_S32_10;
#define V_FIX_S32_10(val)      (long signed int)((double)(((double)val)*1024))
#define S_FIX_S32_10           10

/* power-of-two range: [-1048576 , 1048575.9995117187] , Res = 0.00048828125 */
typedef long signed int        T_FIX_S32_11;
#define V_FIX_S32_11(val)      (long signed int)((double)(((double)val)*2048))
#define S_FIX_S32_11           11

/* power-of-two range: [-524288 , 524287.99975585938] , Res = 0.000244140625 */
typedef long signed int        T_FIX_S32_12;
#define V_FIX_S32_12(val)      (long signed int)((double)(((double)val)*4096))
#define S_FIX_S32_12           12

/* power-of-two range: [-262144 , 262143.99987792969] , Res = 0.0001220703125 */
typedef long signed int        T_FIX_S32_13;
#define V_FIX_S32_13(val)      (long signed int)((double)(((double)val)*8192))
#define S_FIX_S32_13           13

/* power-of-two range: [-131072 , 131071.99993896484] , Res = 6.103515625e-005 */
typedef long signed int        T_FIX_S32_14;
#define V_FIX_S32_14(val)      (long signed int)((double)(((double)val)*16384))
#define S_FIX_S32_14           14

/* power-of-two range: [-65536 , 65535.999969482422] , Res = 3.0517578125e-005 */
typedef long signed int        T_FIX_S32_15;
#define V_FIX_S32_15(val)      (long signed int)((double)(((double)val)*32768))
#define S_FIX_S32_15           15

/* power-of-two range: [-32768 , 32767.999984741211] , Res = 1.52587890625e-005 */
typedef long signed int        T_FIX_S32_16;
#define V_FIX_S32_16(val)      (long signed int)((double)(((double)val)*65536))
#define S_FIX_S32_16           16

/* power-of-two range: [-16384 , 16383.999992370605] , Res = 7.62939453125e-006 */
typedef long signed int        T_FIX_S32_17;
#define V_FIX_S32_17(val)      (long signed int)((double)(((double)val)*131072))
#define S_FIX_S32_17           17

/* power-of-two range: [-8192 , 8191.9999961853027] , Res = 3.814697265625e-006 */
typedef long signed int        T_FIX_S32_18;
#define V_FIX_S32_18(val)      (long signed int)((double)(((double)val)*262144))
#define S_FIX_S32_18           18

/* power-of-two range: [-4096 , 4095.9999980926514] , Res = 1.9073486328125e-006 */
typedef long signed int        T_FIX_S32_19;
#define V_FIX_S32_19(val)      (long signed int)((double)(((double)val)*524288))
#define S_FIX_S32_19           19

/* power-of-two range: [-2048 , 2047.9999990463257] , Res = 9.5367431640625e-007 */
typedef long signed int        T_FIX_S32_20;
#define V_FIX_S32_20(val)      (long signed int)((double)(((double)val)*1048576))
#define S_FIX_S32_20           20

/* power-of-two range: [-1024 , 1023.9999995231628] , Res = 4.76837158203125e-007 */
typedef long signed int        T_FIX_S32_21;
#define V_FIX_S32_21(val)      (long signed int)((double)(((double)val)*2097152))
#define S_FIX_S32_21           21

/* power-of-two range: [-512 , 511.99999976158142] , Res = 2.384185791015625e-007 */
typedef long signed int        T_FIX_S32_22;
#define V_FIX_S32_22(val)      (long signed int)((double)(((double)val)*4194304))
#define S_FIX_S32_22           22

/* power-of-two range: [-256 , 255.99999988079071] , Res = 1.1920928955078125e-007 */
typedef long signed int        T_FIX_S32_23;
#define V_FIX_S32_23(val)      (long signed int)((double)(((double)val)*8388608))
#define S_FIX_S32_23           23

/* power-of-two range: [-128 , 127.99999994039536] , Res = 5.9604644775390625e-008 */
typedef long signed int        T_FIX_S32_24;
#define V_FIX_S32_24(val)      (long signed int)((double)(((double)val)*16777216))
#define S_FIX_S32_24           24

/* power-of-two range: [-64 , 63.999999970197678] , Res = 2.9802322387695313e-008 */
typedef long signed int        T_FIX_S32_25;
#define V_FIX_S32_25(val)      (long signed int)((double)(((double)val)*33554432))
#define S_FIX_S32_25           25

/* power-of-two range: [-32 , 31.999999985098839] , Res = 1.4901161193847656e-008 */
typedef long signed int        T_FIX_S32_26;
#define V_FIX_S32_26(val)      (long signed int)((double)(((double)val)*67108864))
#define S_FIX_S32_26           26

/* power-of-two range: [-16 , 15.999999992549419] , Res = 7.4505805969238281e-009 */
typedef long signed int        T_FIX_S32_27;
#define V_FIX_S32_27(val)      (long signed int)((double)(((double)val)*134217728))
#define S_FIX_S32_27           27

/* power-of-two range: [-8 , 7.9999999962747097] , Res = 3.7252902984619141e-009 */
typedef long signed int        T_FIX_S32_28;
#define V_FIX_S32_28(val)      (long signed int)((double)(((double)val)*268435456))
#define S_FIX_S32_28           28

/* power-of-two range: [-4 , 3.9999999981373549] , Res = 1.862645149230957e-009 */
typedef long signed int        T_FIX_S32_29;
#define V_FIX_S32_29(val)      (long signed int)((double)(((double)val)*536870912))
#define S_FIX_S32_29           29

/* power-of-two range: [-2 , 1.9999999990686774] , Res = 9.3132257461547852e-010 */
typedef long signed int        T_FIX_S32_30;
#define V_FIX_S32_30(val)      (long signed int)((double)(((double)val)*1073741824))
#define S_FIX_S32_30           30

/* power-of-two range: [-1 , 0.99999999953433871] , Res = 4.6566128730773926e-010 */
typedef long signed int        T_FIX_S32_31;
#define V_FIX_S32_31(val)      (long signed int)((double)(((double)val)*2147483648))
#define S_FIX_S32_31           31

/* power-of-two range: [-0.5 , 0.49999999976716936] , Res = 2.3283064365386963e-010 */
typedef long signed int        T_FIX_S32_32;
#define V_FIX_S32_32(val)      (long signed int)((double)(((double)val)*4294967296))
#define S_FIX_S32_32           32

/* power-of-two range: [-0.25 , 0.24999999988358468] , Res = 1.1641532182693481e-010 */
typedef long signed int        T_FIX_S32_33;
#define V_FIX_S32_33(val)      (long signed int)((double)(((double)val)*8589934592))
#define S_FIX_S32_33           33

/* power-of-two range: [-0.125 , 0.12499999994179234] , Res = 5.8207660913467407e-011 */
typedef long signed int        T_FIX_S32_34;
#define V_FIX_S32_34(val)      (long signed int)((double)(((double)val)*17179869184))
#define S_FIX_S32_34           34

/* power-of-two range: [-0.0625 , 0.06249999997089617] , Res = 2.9103830456733704e-011 */
typedef long signed int        T_FIX_S32_35;
#define V_FIX_S32_35(val)      (long signed int)((double)(((double)val)*34359738368))
#define S_FIX_S32_35           35

/* power-of-two range: [-0.03125 , 0.031249999985448085] , Res = 1.4551915228366852e-011 */
typedef long signed int        T_FIX_S32_36;
#define V_FIX_S32_36(val)      (long signed int)((double)(((double)val)*68719476736))
#define S_FIX_S32_36           36

/* power-of-two range: [-0.015625 , 0.015624999992724042] , Res = 7.2759576141834259e-012 */
typedef long signed int        T_FIX_S32_37;
#define V_FIX_S32_37(val)      (long signed int)((double)(((double)val)*137438953472))
#define S_FIX_S32_37           37

/* power-of-two range: [-0.0078125 , 0.0078124999963620212] , Res = 3.637978807091713e-012 */
typedef long signed int        T_FIX_S32_38;
#define V_FIX_S32_38(val)      (long signed int)((double)(((double)val)*274877906944))
#define S_FIX_S32_38           38

/* power-of-two range: [-0.00390625 , 0.0039062499981810106] , Res = 1.8189894035458565e-012 */
typedef long signed int        T_FIX_S32_39;
#define V_FIX_S32_39(val)      (long signed int)((double)(((double)val)*549755813888))
#define S_FIX_S32_39           39

/* power-of-two range: [-0.001953125 , 0.0019531249990905053] , Res = 9.0949470177292824e-013 */
typedef long signed int        T_FIX_S32_40;
#define V_FIX_S32_40(val)      (long signed int)((double)(((double)val)*1099511627776))
#define S_FIX_S32_40           40



/**********************************************************************************
 *                                   32bit Unsigned                               *
 **********************************************************************************/

/* power-of-two range: [0 , 1099511627520] , Res = 256 */
typedef long unsigned int      T_FIX_U32_n08;
#define V_FIX_U32_n08(val)     (long unsigned int)((double)(((double)val)*0.00390625))
#define S_FIX_U32_n08          -8

/* power-of-two range: [0 , 549755813760] , Res = 128 */
typedef long unsigned int      T_FIX_U32_n07;
#define V_FIX_U32_n07(val)     (long unsigned int)((double)(((double)val)*0.0078125))
#define S_FIX_U32_n07          -7

/* power-of-two range: [0 , 274877906880] , Res = 64 */
typedef long unsigned int      T_FIX_U32_n06;
#define V_FIX_U32_n06(val)     (long unsigned int)((double)(((double)val)*0.015625))
#define S_FIX_U32_n06          -6

/* power-of-two range: [0 , 137438953440] , Res = 32 */
typedef long unsigned int      T_FIX_U32_n05;
#define V_FIX_U32_n05(val)     (long unsigned int)((double)(((double)val)*0.03125))
#define S_FIX_U32_n05          -5

/* power-of-two range: [0 , 68719476720] , Res = 16 */
typedef long unsigned int      T_FIX_U32_n04;
#define V_FIX_U32_n04(val)     (long unsigned int)((double)(((double)val)*0.0625))
#define S_FIX_U32_n04          -4

/* power-of-two range: [0 , 34359738360] , Res = 8 */
typedef long unsigned int      T_FIX_U32_n03;
#define V_FIX_U32_n03(val)     (long unsigned int)((double)(((double)val)*0.125))
#define S_FIX_U32_n03          -3

/* power-of-two range: [0 , 17179869180] , Res = 4 */
typedef long unsigned int      T_FIX_U32_n02;
#define V_FIX_U32_n02(val)     (long unsigned int)((double)(((double)val)*0.25))
#define S_FIX_U32_n02          -2

/* power-of-two range: [0 , 8589934590] , Res = 2 */
typedef long unsigned int      T_FIX_U32_n01;
#define V_FIX_U32_n01(val)     (long unsigned int)((double)(((double)val)*0.5))
#define S_FIX_U32_n01          -1

/* power-of-two range: [0 , 4294967295] , Res = 1 */
typedef long unsigned int      T_FIX_U32_00;
#define V_FIX_U32_00(val)      (long unsigned int)((double)(((double)val)*1))
#define S_FIX_U32_00           0

/* power-of-two range: [0 , 2147483647.5] , Res = 0.5 */
typedef long unsigned int      T_FIX_U32_01;
#define V_FIX_U32_01(val)      (long unsigned int)((double)(((double)val)*2))
#define S_FIX_U32_01           1

/* power-of-two range: [0 , 1073741823.75] , Res = 0.25 */
typedef long unsigned int      T_FIX_U32_02;
#define V_FIX_U32_02(val)      (long unsigned int)((double)(((double)val)*4))
#define S_FIX_U32_02           2

/* power-of-two range: [0 , 536870911.875] , Res = 0.125 */
typedef long unsigned int      T_FIX_U32_03;
#define V_FIX_U32_03(val)      (long unsigned int)((double)(((double)val)*8))
#define S_FIX_U32_03           3

/* power-of-two range: [0 , 268435455.9375] , Res = 0.0625 */
typedef long unsigned int      T_FIX_U32_04;
#define V_FIX_U32_04(val)      (long unsigned int)((double)(((double)val)*16))
#define S_FIX_U32_04           4

/* power-of-two range: [0 , 134217727.96875] , Res = 0.03125 */
typedef long unsigned int      T_FIX_U32_05;
#define V_FIX_U32_05(val)      (long unsigned int)((double)(((double)val)*32))
#define S_FIX_U32_05           5

/* power-of-two range: [0 , 67108863.984375] , Res = 0.015625 */
typedef long unsigned int      T_FIX_U32_06;
#define V_FIX_U32_06(val)      (long unsigned int)((double)(((double)val)*64))
#define S_FIX_U32_06           6

/* power-of-two range: [0 , 33554431.9921875] , Res = 0.0078125 */
typedef long unsigned int      T_FIX_U32_07;
#define V_FIX_U32_07(val)      (long unsigned int)((double)(((double)val)*128))
#define S_FIX_U32_07           7

/* power-of-two range: [0 , 16777215.99609375] , Res = 0.00390625 */
typedef long unsigned int      T_FIX_U32_08;
#define V_FIX_U32_08(val)      (long unsigned int)((double)(((double)val)*256))
#define S_FIX_U32_08           8

/* power-of-two range: [0 , 8388607.998046875] , Res = 0.001953125 */
typedef long unsigned int      T_FIX_U32_09;
#define V_FIX_U32_09(val)      (long unsigned int)((double)(((double)val)*512))
#define S_FIX_U32_09           9

/* power-of-two range: [0 , 4194303.9990234375] , Res = 0.0009765625 */
typedef long unsigned int      T_FIX_U32_10;
#define V_FIX_U32_10(val)      (long unsigned int)((double)(((double)val)*1024))
#define S_FIX_U32_10           10

/* power-of-two range: [0 , 2097151.9995117188] , Res = 0.00048828125 */
typedef long unsigned int      T_FIX_U32_11;
#define V_FIX_U32_11(val)      (long unsigned int)((double)(((double)val)*2048))
#define S_FIX_U32_11           11

/* power-of-two range: [0 , 1048575.9997558594] , Res = 0.000244140625 */
typedef long unsigned int      T_FIX_U32_12;
#define V_FIX_U32_12(val)      (long unsigned int)((double)(((double)val)*4096))
#define S_FIX_U32_12           12

/* power-of-two range: [0 , 524287.99987792969] , Res = 0.0001220703125 */
typedef long unsigned int      T_FIX_U32_13;
#define V_FIX_U32_13(val)      (long unsigned int)((double)(((double)val)*8192))
#define S_FIX_U32_13           13

/* power-of-two range: [0 , 262143.99993896484] , Res = 6.103515625e-005 */
typedef long unsigned int      T_FIX_U32_14;
#define V_FIX_U32_14(val)      (long unsigned int)((double)(((double)val)*16384))
#define S_FIX_U32_14           14

/* power-of-two range: [0 , 131071.99996948242] , Res = 3.0517578125e-005 */
typedef long unsigned int      T_FIX_U32_15;
#define V_FIX_U32_15(val)      (long unsigned int)((double)(((double)val)*32768))
#define S_FIX_U32_15           15

/* power-of-two range: [0 , 65535.999984741211] , Res = 1.52587890625e-005 */
typedef long unsigned int      T_FIX_U32_16;
#define V_FIX_U32_16(val)      (long unsigned int)((double)(((double)val)*65536))
#define S_FIX_U32_16           16

/* power-of-two range: [0 , 32767.999992370605] , Res = 7.62939453125e-006 */
typedef long unsigned int      T_FIX_U32_17;
#define V_FIX_U32_17(val)      (long unsigned int)((double)(((double)val)*131072))
#define S_FIX_U32_17           17

/* power-of-two range: [0 , 16383.999996185303] , Res = 3.814697265625e-006 */
typedef long unsigned int      T_FIX_U32_18;
#define V_FIX_U32_18(val)      (long unsigned int)((double)(((double)val)*262144))
#define S_FIX_U32_18           18

/* power-of-two range: [0 , 8191.9999980926514] , Res = 1.9073486328125e-006 */
typedef long unsigned int      T_FIX_U32_19;
#define V_FIX_U32_19(val)      (long unsigned int)((double)(((double)val)*524288))
#define S_FIX_U32_19           19

/* power-of-two range: [0 , 4095.9999990463257] , Res = 9.5367431640625e-007 */
typedef long unsigned int      T_FIX_U32_20;
#define V_FIX_U32_20(val)      (long unsigned int)((double)(((double)val)*1048576))
#define S_FIX_U32_20           20

/* power-of-two range: [0 , 2047.9999995231628] , Res = 4.76837158203125e-007 */
typedef long unsigned int      T_FIX_U32_21;
#define V_FIX_U32_21(val)      (long unsigned int)((double)(((double)val)*2097152))
#define S_FIX_U32_21           21

/* power-of-two range: [0 , 1023.9999997615814] , Res = 2.384185791015625e-007 */
typedef long unsigned int      T_FIX_U32_22;
#define V_FIX_U32_22(val)      (long unsigned int)((double)(((double)val)*4194304))
#define S_FIX_U32_22           22

/* power-of-two range: [0 , 511.99999988079071] , Res = 1.1920928955078125e-007 */
typedef long unsigned int      T_FIX_U32_23;
#define V_FIX_U32_23(val)      (long unsigned int)((double)(((double)val)*8388608))
#define S_FIX_U32_23           23

/* power-of-two range: [0 , 255.99999994039536] , Res = 5.9604644775390625e-008 */
typedef long unsigned int      T_FIX_U32_24;
#define V_FIX_U32_24(val)      (long unsigned int)((double)(((double)val)*16777216))
#define S_FIX_U32_24           24

/* power-of-two range: [0 , 127.99999997019768] , Res = 2.9802322387695313e-008 */
typedef long unsigned int      T_FIX_U32_25;
#define V_FIX_U32_25(val)      (long unsigned int)((double)(((double)val)*33554432))
#define S_FIX_U32_25           25

/* power-of-two range: [0 , 63.999999985098839] , Res = 1.4901161193847656e-008 */
typedef long unsigned int      T_FIX_U32_26;
#define V_FIX_U32_26(val)      (long unsigned int)((double)(((double)val)*67108864))
#define S_FIX_U32_26           26

/* power-of-two range: [0 , 31.999999992549419] , Res = 7.4505805969238281e-009 */
typedef long unsigned int      T_FIX_U32_27;
#define V_FIX_U32_27(val)      (long unsigned int)((double)(((double)val)*134217728))
#define S_FIX_U32_27           27

/* power-of-two range: [0 , 15.99999999627471] , Res = 3.7252902984619141e-009 */
typedef long unsigned int      T_FIX_U32_28;
#define V_FIX_U32_28(val)      (long unsigned int)((double)(((double)val)*268435456))
#define S_FIX_U32_28           28

/* power-of-two range: [0 , 7.9999999981373549] , Res = 1.862645149230957e-009 */
typedef long unsigned int      T_FIX_U32_29;
#define V_FIX_U32_29(val)      (long unsigned int)((double)(((double)val)*536870912))
#define S_FIX_U32_29           29

/* power-of-two range: [0 , 3.9999999990686774] , Res = 9.3132257461547852e-010 */
typedef long unsigned int      T_FIX_U32_30;
#define V_FIX_U32_30(val)      (long unsigned int)((double)(((double)val)*1073741824))
#define S_FIX_U32_30           30

/* power-of-two range: [0 , 1.9999999995343387] , Res = 4.6566128730773926e-010 */
typedef long unsigned int      T_FIX_U32_31;
#define V_FIX_U32_31(val)      (long unsigned int)((double)(((double)val)*2147483648))
#define S_FIX_U32_31           31

/* power-of-two range: [0 , 0.99999999976716936] , Res = 2.3283064365386963e-010 */
typedef long unsigned int      T_FIX_U32_32;
#define V_FIX_U32_32(val)      (long unsigned int)((double)(((double)val)*4294967296))
#define S_FIX_U32_32           32

/* power-of-two range: [0 , 0.49999999988358468] , Res = 1.1641532182693481e-010 */
typedef long unsigned int      T_FIX_U32_33;
#define V_FIX_U32_33(val)      (long unsigned int)((double)(((double)val)*8589934592))
#define S_FIX_U32_33           33

/* power-of-two range: [0 , 0.24999999994179234] , Res = 5.8207660913467407e-011 */
typedef long unsigned int      T_FIX_U32_34;
#define V_FIX_U32_34(val)      (long unsigned int)((double)(((double)val)*17179869184))
#define S_FIX_U32_34           34

/* power-of-two range: [0 , 0.12499999997089617] , Res = 2.9103830456733704e-011 */
typedef long unsigned int      T_FIX_U32_35;
#define V_FIX_U32_35(val)      (long unsigned int)((double)(((double)val)*34359738368))
#define S_FIX_U32_35           35

/* power-of-two range: [0 , 0.062499999985448085] , Res = 1.4551915228366852e-011 */
typedef long unsigned int      T_FIX_U32_36;
#define V_FIX_U32_36(val)      (long unsigned int)((double)(((double)val)*68719476736))
#define S_FIX_U32_36           36

/* power-of-two range: [0 , 0.031249999992724042] , Res = 7.2759576141834259e-012 */
typedef long unsigned int      T_FIX_U32_37;
#define V_FIX_U32_37(val)      (long unsigned int)((double)(((double)val)*137438953472))
#define S_FIX_U32_37           37

/* power-of-two range: [0 , 0.015624999996362021] , Res = 3.637978807091713e-012 */
typedef long unsigned int      T_FIX_U32_38;
#define V_FIX_U32_38(val)      (long unsigned int)((double)(((double)val)*274877906944))
#define S_FIX_U32_38           38

/* power-of-two range: [0 , 0.0078124999981810106] , Res = 1.8189894035458565e-012 */
typedef long unsigned int      T_FIX_U32_39;
#define V_FIX_U32_39(val)      (long unsigned int)((double)(((double)val)*549755813888))
#define S_FIX_U32_39           39

/* power-of-two range: [0 , 0.0039062499990905053] , Res = 9.0949470177292824e-013 */
typedef long unsigned int      T_FIX_U32_40;
#define V_FIX_U32_40(val)      (long unsigned int)((double)(((double)val)*1099511627776))
#define S_FIX_U32_40           40

 
#endif /* T_FIX_X_Y_H */
 
 
/*************************************************************************************************
*
* Revision History
*
* Rev.  YYMMDD Who RSM# Changes
* ----  ------ --- ---- ------------------------------------------------------------------------
* 1.0   110321 mm  9300 Original implementation as part of introducing new auto-code process.
*
*************************************************************************************************/
