#ifndef IO_CONFIG_SPARK_H
#define IO_CONFIG_SPARK_H



#define SPARK_DWELL_ABSOLUTE_MAXVALUE_IN_SEC            ( 0.02 )
#define SPARK_DWELL_LIMIT_IN_REFPERIOD_PERCENT          (  0.8 )
#define SPARK_DWELL_MPTAC_MAX_FALL_ANGLE_IN_TOOTHCOUNT  (    2 )

#define  SPARK_INITIAL_MODE   SPARK_SIMULTANEOUS_MODE
#define  SPARK_SELECT_MAX   (1)

#define EST_SELECT_DEVICE_CIC  ( 0 )
#define EST_SELECT_DEVICE_PSVI ( 1 )
#define EST_SELECT_DEVICE_ESCI3 ( 2 )

#define EST_SELECT_METHOD EST_SELECT_DEVICE_ESCI3

#define SPARK_MAX_CYLINDERS                  CRANK_CONFIG_NUMBER_OF_CYLINDERS


#endif // IO_SPARK_CONFIG_H

